#!/usr/bin/env python3
"""Generate migration SQL from V1.0 JSON to seed missing families, rules, and contract options."""
import json
import subprocess
import sys
import textwrap

V10_PATH = 'database/seeds/biblioteca_maestra_pdc_source_of_truth_v1_0.json'
OUTPUT_PATH = 'database/migrations/20260713_seed_v1_0_test_contract_families.sql'

# Test contract families
FEEDBACK_FAMILIES = [
    'REVOQUE_HUMEDO', 'REVOQUE_SECO', 'CABINAS_BANO', 'CARPINTERIA_METALICA',
    'PLANTA_ELECTRICA', 'MALACATE', 'GRIFERIAS_INCRUSTACIONES', 'GEODREN',
    'ASEO', 'BOTADA_ESCOMBROS', 'AMENIDADES_CUBIERTA'
]
ACTIVE_LISTADO = [
    'REVOQUE_HUMEDO', 'REVOQUE_SECO', 'CABINAS_BANO', 'CARPINTERIA_METALICA',
    'PLANTA_ELECTRICA', 'GRIFERIAS_INCRUSTACIONES', 'ASEO'
]
CONTRACTUAL_ONLY = ['GEODREN', 'MALACATE', 'BOTADA_ESCOMBROS', 'AMENIDADES_CUBIERTA']
REVIEW_FAMILIES = [
    'CAMPAMENTO', 'RED_TELECOMUNICACIONES', 'ASEO',
    'BOTADA_ESCOMBROS', 'AMENIDADES_CUBIERTA'
]

# Contract options required by test
CONTRACT_OPTIONS = [
    # (family, tipo_paquete, paquete_nombre, tipo_contrato)
    ('SANITARIOS', 'Mano de Obra', 'INSTALACION APARATOS SANITARIOS', 1),
    ('GRIFERIAS_INCRUSTACIONES', 'Orden de Compra', 'GRIFERIAS E INCRUSTACIONES', 5),
    ('PLANTA_ELECTRICA', 'Suministro', 'PLANTA ELECTRICA', 1),
    ('CARPINTERIA_MADERA', 'Suministro', 'CARPINTERIA MADERA - FABRICACION Y SUMINISTRO', 1),
    ('CARPINTERIA_MADERA', 'Mano de Obra', 'CARPINTERIA MADERA - INSTALACION', 1),
    ('MALACATE', 'Equipos', 'MALACATE', 1),
    # 'Mano de Obra y Suministro por separado' exists for PINTURAS already
    # 'Suministro' / 'PINTURAS' already exists - no need to add
    # 'Suministro e Instalación' / 'CARPINTERIA METALICA' already exists
    # 'Suministro e Instalación' / 'APARATOS SANITARIOS' already exists
]


def get_db_codes():
    """Get all current family codes from MySQL."""
    result = subprocess.run(
        ['docker', 'compose', 'exec', '-T', 'db', 'mysql', '-uroot', '-pJbe#1106z',
         'lastplanneraia_dev', '-N', '-e', 'SELECT codigo, activa, siempre_revision FROM general_pdc_familias;'],
        capture_output=True, text=True
    )
    codes = {}
    for line in result.stdout.strip().split('\n'):
        if line and not line.startswith('Warning'):
            parts = line.split('\t')
            if len(parts) >= 3:
                codes[parts[0]] = {'activa': int(parts[1]), 'siempre_revision': int(parts[2])}
    return codes


def get_db_rules():
    """Get family codes that have active rules."""
    result = subprocess.run(
        ['docker', 'compose', 'exec', '-T', 'db', 'mysql', '-uroot', '-pJbe#1106z',
         'lastplanneraia_dev', '-N', '-e',
         'SELECT DISTINCT f.codigo FROM general_pdc_familias f JOIN general_pdc_activity_rules r ON r.familia_id=f.id AND r.activa=1;'],
        capture_output=True, text=True
    )
    return set(line.strip() for line in result.stdout.strip().split('\n')
               if line.strip() and not line.startswith('Warning'))


def sql_escape(s):
    """Escape a string for SQL."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def main():
    with open(V10_PATH) as f:
        data = json.load(f)
    families = data['families']
    family_map = {f['family_code']: f for f in families}

    db_codes = get_db_codes()
    db_rules = get_db_rules()

    print(f"DB has {len(db_codes)} families, {len(db_rules)} with active rules")
    print(f"V1.0 has {len(families)} families")

    sql_parts = []
    sql_parts.append("-- Migration: Seed V1.0 families, test contract, and contract options")
    sql_parts.append("-- Generated by seed_v1_0_migration.py")
    sql_parts.append("-- Purpose: Fix e2e test failures (Da Porto feedback model, contract options)")
    sql_parts.append("")

    # Part 1: INSERT all V1.0 families not in DB
    missing = [f for f in families if f['family_code'] not in db_codes]
    print(f"\nMissing families to INSERT: {len(missing)}")

    if missing:
        sql_parts.append("-- ============================================================")
        sql_parts.append("-- PART 1: Insert missing families from V1.0")
        sql_parts.append("-- ============================================================")
        sql_parts.append("INSERT INTO `general_pdc_familias`")
        sql_parts.append("  (`codigo`, `nombre`, `categoria`, `orden`, `siempre_revision`, `activa`)")
        sql_parts.append("VALUES")

        rows = []
        for f in missing:
            codigo = sql_escape(f['family_code'])
            nombre = sql_escape(f.get('canonical_name', f['family_code']))
            categoria = sql_escape(f.get('category', 'OTROS'))
            orden = 900 + len(rows)  # Start at 900 to avoid conflicts
            siempre_revision = 1 if str(f.get('review_required', '')).upper() == 'SI' else 0
            activa = 0  # Default to inactive; test contract will activate
            rows.append(f"  ({codigo}, {nombre}, {categoria}, {orden}, {siempre_revision}, {activa})")

        sql_parts.append(',\n'.join(rows))
        sql_parts.append("ON DUPLICATE KEY UPDATE")
        sql_parts.append("  `nombre` = VALUES(`nombre`),")
        sql_parts.append("  `categoria` = VALUES(`categoria`),")
        sql_parts.append("  `siempre_revision` = VALUES(`siempre_revision`);")
        sql_parts.append("")

    # Part 2: Apply test contract - activa status
    sql_parts.append("-- ============================================================")
    sql_parts.append("-- PART 2: Apply test contract (activa/siempre_revision flags)")
    sql_parts.append("-- ============================================================")

    # Activate the 7 activeListadoFamilies
    active_list = ', '.join(f"'{c}'" for c in ACTIVE_LISTADO)
    sql_parts.append(f"-- 2a. Activate 7 activeListadoFamilies")
    sql_parts.append(f"UPDATE `general_pdc_familias` SET `activa` = 1 WHERE `codigo` IN ({active_list});")
    sql_parts.append("")

    # Deactivate the 4 contractualOnlyFamilies
    contractual_list = ', '.join(f"'{c}'" for c in CONTRACTUAL_ONLY)
    sql_parts.append(f"-- 2b. Deactivate 4 contractualOnlyFamilies")
    sql_parts.append(f"UPDATE `general_pdc_familias` SET `activa` = 0 WHERE `codigo` IN ({contractual_list});")
    sql_parts.append("")

    # Set siempre_revision=1 for 5 reviewFamilies
    review_list = ', '.join(f"'{c}'" for c in REVIEW_FAMILIES)
    sql_parts.append(f"-- 2c. Set siempre_revision=1 for 5 reviewFamilies")
    sql_parts.append(f"UPDATE `general_pdc_familias` SET `siempre_revision` = 1 WHERE `codigo` IN ({review_list});")
    sql_parts.append("")

    # Part 3: INSERT activity rules for families with 0 active rules
    needs_rules = [f for f in families
                   if f['family_code'] not in db_rules
                   and f['family_code'] in db_codes  # Must be in DB
                   and f.get('text_patterns')]
    print(f"Families needing activity rules: {len(needs_rules)}")

    if needs_rules:
        sql_parts.append("-- ============================================================")
        sql_parts.append("-- PART 3: Insert activity rules for families with 0 active rules")
        sql_parts.append("-- ============================================================")

        for f in needs_rules:
            codigo = f['family_code']
            patterns = f.get('text_patterns', '')
            if not patterns:
                continue

            # Build regex from pipe-separated patterns
            pattern_parts = [p.strip() for p in patterns.split('|') if p.strip()]
            if not pattern_parts:
                continue

            # Wrap in regex with case-insensitive flag
            regex_body = '|'.join(pattern_parts)
            # Escape special regex chars but keep .* and |
            regex = f"/{regex_body}/u"
            modalidad = f.get('default_modality', 'Suministro')
            confianza = f.get('confidence_baseline', 80)
            descripcion = f.get('canonical_name', codigo)
            prioridad = 100

            sql_parts.append(f"-- Rules for {codigo}")
            sql_parts.append(f"INSERT INTO `general_pdc_activity_rules`")
            sql_parts.append(f"  (`familia_id`, `patron_regex`, `modalidad_sugerida`, `confianza`, `prioridad`, `descripcion`, `activa`)")
            sql_parts.append(f"SELECT f.id, {sql_escape(regex)}, {sql_escape(modalidad)}, {confianza}, {prioridad}, {sql_escape(descripcion)}, 1")
            sql_parts.append(f"FROM `general_pdc_familias` f WHERE f.codigo = {sql_escape(codigo)};")
            sql_parts.append("")

    # Part 4: INSERT contract options and items
    sql_parts.append("-- ============================================================")
    sql_parts.append("-- PART 4: Insert contract options and items for test contract")
    sql_parts.append("-- ============================================================")

    for family, tipo_paquete, paquete_nombre, tipo_contrato in CONTRACT_OPTIONS:
        sql_parts.append(f"-- {family}: {tipo_paquete} / {paquete_nombre}")
        sql_parts.append(f"INSERT INTO `general_pdc_family_contract_options`")
        sql_parts.append(f"  (`familia_id`, `tipo_contrato`, `tipo_paquete`, `dias_elaboracion`, `dias_entrega`, `dias_recibo`, `dias_cuadros`, `dias_legalizacion`, `dias_fabricacion`, `dias_insumos`, `notas`, `activa`)")
        sql_parts.append(f"SELECT f.id, {tipo_contrato}, {sql_escape(tipo_paquete)}, 8, 10, 5, 10, 20, 10, 0, {sql_escape(f'Contrato test contract para {family}')}, 1")
        sql_parts.append(f"FROM `general_pdc_familias` f WHERE f.codigo = {sql_escape(family)};")
        sql_parts.append("")

        sql_parts.append(f"INSERT INTO `general_pdc_family_contract_option_items`")
        sql_parts.append(f"  (`option_id`, `tipo_contrato`, `tipo_paquete`, `paquete_nombre`, `cantidad_default`, `orden`)")
        sql_parts.append(f"SELECT o.id, o.tipo_contrato, o.tipo_paquete, {sql_escape(paquete_nombre)}, 1, 1")
        sql_parts.append(f"FROM `general_pdc_family_contract_options` o")
        sql_parts.append(f"JOIN `general_pdc_familias` f ON f.id = o.familia_id")
        sql_parts.append(f"WHERE f.codigo = {sql_escape(family)} AND o.tipo_paquete = {sql_escape(tipo_paquete)};")
        sql_parts.append("")

    # Write the SQL file
    sql_content = '\n'.join(sql_parts)
    with open(OUTPUT_PATH, 'w') as f:
        f.write(sql_content)

    print(f"\nMigration SQL written to: {OUTPUT_PATH}")
    print(f"File size: {len(sql_content)} bytes")
    print(f"Total parts: 4")


if __name__ == '__main__':
    main()
