import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const drawer = read('public/js/modules/aia_ui/nav_drawer.js');
const css = read('public/css/navbar.css');
const lpsCss = read('public/css/handsontable-module.css');
const lpsDrawer = read('public/js/modules/lps_drawer.js');
const lpsView = read('views/partials/drawer_unificado.php');
const weeklyView = read('views/programacion-semanal/programacion_semanal.view.php');
const exceptions = JSON.parse(read('docs/design-system/exceptions.json'));
const theme = read('public/js/modules/aia_ui/theme.js');
const commonLoader = read('public/js/linksComunesHead2.js');
const loginView = read('views/auth/login.view.php');
const projectSelectorView = read('views/core/project_selector.view.php');
const renderers = [
  read('src/View/Components/NavbarComponent.php'),
  read('public/js/cargarDatosGeneralesPagina2.js'),
];

assert.match(drawer, /key === 'Escape'/);
assert.match(drawer, /aria-expanded/);
assert.match(drawer, /focus\(\)/);
assert.match(drawer, /key === 'Tab'/);
assert.match(drawer, /setTimeout\(function \(\) \{ ui\.close\.focus\(\); \}, 450\)/);
assert.match(drawer, /function isVisibleFocusable\(element\)/);
assert.match(drawer, /getClientRects\(\)\.length/);
assert.match(drawer, /aria-hidden/);
assert.match(drawer, /ui\.drawer\.setAttribute\('aria-hidden', 'true'\)/);
assert.match(drawer, /ui\.drawer\.setAttribute\('aria-hidden', 'false'\)/);
assert.match(drawer, /ui\.drawer\.removeAttribute\('aria-modal'\)/);
assert.match(drawer, /ui\.drawer\.removeAttribute\('role'\)/);
assert.match(drawer, /function syncResponsiveSemantics\(isDesktop\)/);
assert.match(drawer, /function boot\(\)/);
assert.match(drawer, /DOMContentLoaded/);
assert.match(css, /\.close-drawer[\s\S]*?min-width:\s*var\(--ds-target-min\)/);
assert.match(css, /\.user-island-actions[\s\S]*?\.island-btn\s*\{[^}]*min-height:\s*var\(--ds-target-min\)/s);
assert.match(css, /\.navbar-collapse-drawer[\s\S]*?max-width:\s*100vw/);
assert.match(css, /\.navbar-collapse-drawer \.nav-link\s*\{[^}]*min-height:\s*var\(--ds-target-min\)/s);
assert.match(css, /\.dropdown-menu\[aria-labelledby="userDropdown"\] \.dropdown-item\s*\{[^}]*min-height:\s*var\(--ds-target-min\)/s);
assert.match(css, /\.context-bar\s*\{[^}]*position:\s*sticky[^}]*top:\s*var\(--navbar-height\)/s);
assert.match(css, /\.shell-nav-spacer\s*\{[^}]*height:\s*var\(--navbar-height\)/s);
for (const renderer of renderers) {
  assert.match(renderer, /aria-controls=/);
  assert.match(renderer, /aria-label=["']Cerrar menú/);
}
assert.doesNotMatch(renderers[1], /context-bar fixed-top" style=/);
assert.doesNotMatch(renderers[1], /context-bar fixed-top/);
assert.doesNotMatch(renderers[1], /<div style="height: 100px;/);
assert.doesNotMatch(renderers[0], /<div style="height: 70px;/);
assert.match(renderers[1], /shell-nav-spacer[\s\S]*context-bar/);
assert.doesNotMatch(renderers[1], /shell-context-spacer/);
assert.match(lpsCss, /\.lps-drawer\s*\{[^}]*background:\s*var\(--ds-active-bg-page\)/s);
assert.match(lpsCss, /\.lps-drawer-header\s*\{[^}]*background:\s*var\(--ds-active-surface-raised\)/s);
assert.match(lpsCss, /\.lps-card-glass\s*\{[^}]*background:\s*var\(--ds-active-surface-raised\)/s);
assert.match(lpsDrawer, /event\.key === 'Escape'/);
assert.match(lpsDrawer, /aria-hidden/);
assert.match(lpsDrawer, /sidebarTrigger\.focus\(\)/);
assert.match(lpsDrawer, /event\.key === 'Tab'/);
assert.match(lpsDrawer, /lpsFocusableSelector/);
assert.match(lpsDrawer, /event\.shiftKey/);
assert.match(lpsView, /<button[^>]*id="lps_sidebar_trigger"[^>]*aria-controls="lps_drawer"[^>]*aria-expanded="false"/s);
assert.match(lpsView, /id="lps_drawer"[^>]*aria-hidden="true"/s);
assert.match(weeklyView, /handsontable-module\.css\?v=20260711foundation5/);
assert.match(weeklyView, /lps_drawer\.js\?v=20260711foundation5/);
const shellBudget = exceptions.pathBudgets.find((budget) => budget.name === 'foundation-shell');
assert.ok(shellBudget, 'Foundation/Shell must have an explicit debt budget');
assert.ok(shellBudget.paths.includes('public/css/navbar.css'));
assert.ok(shellBudget.paths.includes('views/partials/drawer_unificado.php'));
assert.match(theme, /bindThemeSwitches/);
assert.match(theme, /function boot\(\)/);
assert.match(theme, /document\.readyState === 'loading'/);
assert.match(theme, /DOMContentLoaded/);
assert.match(theme, /window\.AiaDesignSystem\.bindThemeSwitches\(document\)/);
assert.match(theme, /aia-theme-ready/);
assert.doesNotMatch(renderers[0], /function currentTheme\(/);
assert.doesNotMatch(renderers[1], /function currentTheme\(/);
assert.match(renderers[0], /AiaDesignSystem\.bindThemeSwitches\(document\)/);
assert.match(renderers[1], /AiaDesignSystem\.bindThemeSwitches\(document\)/);
assert.match(renderers[0], /typeof window\.AiaDesignSystem\.bindThemeSwitches === 'function'/);
assert.match(renderers[1], /typeof window\.AiaDesignSystem\.bindThemeSwitches === 'function'/);
assert.match(renderers[0], /aia-theme-ready/);
assert.match(renderers[1], /aia-theme-ready/);
assert.match(commonLoader, /theme\.js\?v=20260711foundation5/);
assert.match(commonLoader, /nav_drawer\.js\?v=20260711foundation5/);
assert.match(commonLoader, /tokens\.css\?v=20260711foundation5/);
assert.doesNotMatch(renderers[0], /nav_drawer\.js\?v=<\?php echo time\(\)/);
assert.match(loginView, /theme\.js\?v=<\?= filemtime\(/);
assert.match(projectSelectorView, /theme\.js\?v=<\?= filemtime\(/);
