-- ============================================================================
-- 003_seed_rbac_data.sql
-- Migración Quirúrgica: Datos semilla (RBAC, notificaciones, diccionarios)
-- Compatible: MySQL 8.0+ / 8.4.6 (Producción SiteGround)
-- Fecha: 2026-03-26
-- ============================================================================
-- POLÍTICA: INSERT IGNORE → seguro re-ejecutar (no duplica registros)
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------
-- 1. rbac_roles (12 roles)
-- -----------------------------------------------
INSERT IGNORE INTO `rbac_roles` (`code`, `name`, `description`, `is_admin_area`, `is_system_admin`, `is_legacy`, `status`, `sort_order`, `created_at`, `updated_at`) VALUES
('A','Administrador','Control total incluyendo administracion del sistema',1,1,0,1,10,NOW(),NOW()),
('C','Subcontratista','Sin acciones in-app en fase inicial',0,0,0,1,90,NOW(),NOW()),
('D','Director Funcional','Control funcional total sin administracion del sistema',0,0,0,1,20,NOW(),NOW()),
('DCV','Profesional DCV','Misma politica de permisos que rol R',0,0,0,1,40,NOW(),NOW()),
('G','Ambiental','Edita solo CIC por especialidad',0,0,0,1,60,NOW(),NOW()),
('OT','Oficina Tecnica','Edita solo Listado/Contratos/PDC y visualiza el resto',0,0,0,1,50,NOW(),NOW()),
('P','Planeacion (Legacy alias)','Alias historico de D',0,0,1,1,96,NOW(),NOW()),
('R','Residente de Obra','Edita modulos LPS y visualiza Listado/Contratos/PDC',0,0,0,1,30,NOW(),NOW()),
('S','SST','Edita solo CIC por especialidad',0,0,0,1,70,NOW(),NOW()),
('SG','SST + Ambiental','Edita solo CIC por especialidad',0,0,0,1,80,NOW(),NOW()),
('U','Usuario (Legacy alias)','Alias historico de V',0,0,1,1,97,NOW(),NOW()),
('V','Visualizador','Rol de solo lectura para transicion',0,0,1,1,95,NOW(),NOW());

-- -----------------------------------------------
-- 2. rbac_permissions (43 permisos)
-- -----------------------------------------------
INSERT IGNORE INTO `rbac_permissions` (`permission_key`, `module_name`, `action_name`, `description`, `is_write`, `is_sensitive`, `created_at`, `updated_at`) VALUES
('admin.auditoria.ver','admin','ver_auditoria','Ver auditoria',0,1,NOW(),NOW()),
('admin.miembros.gestionar','admin','gestionar_miembros','Gestion de miembros',1,1,NOW(),NOW()),
('admin.panel.acceso','admin','acceso','Acceso al panel admin',0,1,NOW(),NOW()),
('admin.permisos.gestionar','admin','gestionar_permisos','Gestion de permisos',1,1,NOW(),NOW()),
('admin.proyectos.gestionar','admin','gestionar_proyectos','Gestion de proyectos',1,1,NOW(),NOW()),
('admin.usuarios.gestionar','admin','gestionar_usuarios','Gestion de usuarios',1,1,NOW(),NOW()),
('lps.cic.editar','lps','cic_editar','Editar CIC',1,0,NOW(),NOW()),
('lps.cic.ver','lps','cic_ver','Ver CIC',0,0,NOW(),NOW()),
('lps.cnc.editar','lps','cnc_editar','Editar CNC',1,0,NOW(),NOW()),
('lps.cnc.ver','lps','cnc_ver','Ver CNC',0,0,NOW(),NOW()),
('lps.cnp.editar','lps','cnp_editar','Editar CNP',1,0,NOW(),NOW()),
('lps.cnp.ver','lps','cnp_ver','Ver CNP',0,0,NOW(),NOW()),
('lps.contratos.editar','lps','contratos_editar','Editar contratos',1,0,NOW(),NOW()),
('lps.contratos.ver','lps','contratos_ver','Ver contratos',0,0,NOW(),NOW()),
('lps.control_cambios.editar','lps','control_cambios_editar','Editar control de cambios',1,0,NOW(),NOW()),
('lps.control_cambios.ver','lps','control_cambios_ver','Ver control de cambios',0,0,NOW(),NOW()),
('lps.indicadores.ver','lps','indicadores_ver','Ver indicadores',0,0,NOW(),NOW()),
('lps.listado_actividades.editar','lps','listado_actividades_editar','Editar listado de actividades',1,0,NOW(),NOW()),
('lps.listado_actividades.ver','lps','listado_actividades_ver','Ver listado de actividades',0,0,NOW(),NOW()),
('lps.paquetes_contratacion.editar','lps','paquetes_contratacion_editar','Editar paquetes de contratacion',1,0,NOW(),NOW()),
('lps.paquetes_contratacion.ver','lps','paquetes_contratacion_ver','Ver paquetes de contratacion',0,0,NOW(),NOW()),
('lps.pdc.editar','lps','pdc_editar','Editar PDC',1,0,NOW(),NOW()),
('lps.pdc.ver','lps','pdc_ver','Ver PDC',0,0,NOW(),NOW()),
('lps.profesionales.editar','lps','profesionales_editar','Editar profesionales',1,0,NOW(),NOW()),
('lps.profesionales.ver','lps','profesionales_ver','Ver profesionales',0,0,NOW(),NOW()),
('lps.programa_general_actualizar.editar','lps','programa_general_actualizar_editar','Editar programa general actualizar',1,0,NOW(),NOW()),
('lps.programa_general_actualizar.ver','lps','programa_general_actualizar_ver','Ver programa general actualizar',0,0,NOW(),NOW()),
('lps.programa_general.editar','lps','programa_general_editar','Editar programa general',1,0,NOW(),NOW()),
('lps.programa_general.ver','lps','programa_general_ver','Ver programa general',0,0,NOW(),NOW()),
('lps.programacion_intermedia.editar','lps','programacion_intermedia_editar','Editar programacion intermedia',1,0,NOW(),NOW()),
('lps.programacion_intermedia.ver','lps','programacion_intermedia_ver','Ver programacion intermedia',0,0,NOW(),NOW()),
('lps.programacion_semanal.editar','lps','programacion_semanal_editar','Editar programacion semanal',1,0,NOW(),NOW()),
('lps.programacion_semanal.ver','lps','programacion_semanal_ver','Ver programacion semanal',0,0,NOW(),NOW()),
('lps.reportes.generar','lps','reportes_generar','Generar reportes',0,0,NOW(),NOW()),
('lps.semana.crear','lps','semana_crear','Crear nuevas semanas en el proyecto',1,0,NOW(),NOW()),
('lps.subcontratistas.editar','lps','subcontratistas_editar','Editar subcontratistas',1,0,NOW(),NOW()),
('lps.subcontratistas.ver','lps','subcontratistas_ver','Ver subcontratistas',0,0,NOW(),NOW()),
('notificaciones.admin_seguridad','notificaciones','admin_seguridad','Recibir alertas de administracion y seguridad',0,1,NOW(),NOW()),
('notificaciones.cic_especialidad','notificaciones','cic_especialidad','Recibir alertas CIC por especialidad',0,0,NOW(),NOW()),
('notificaciones.ejecutivas','notificaciones','ejecutivas','Recibir alertas ejecutivas',0,0,NOW(),NOW()),
('notificaciones.gestion_pdc_contratos','notificaciones','gestion_pdc_contratos','Recibir alertas de gestion PDC y contratos',0,0,NOW(),NOW()),
('notificaciones.lps_operativas','notificaciones','lps_operativas','Recibir alertas operativas LPS',0,0,NOW(),NOW()),
('notificaciones.preferencias_personales','notificaciones','preferencias_personales','Gestionar preferencias personales de notificacion',0,0,NOW(),NOW()),
('notificaciones.resumen_semanal','notificaciones','resumen_semanal','Recibir resumen semanal',0,0,NOW(),NOW());

-- -----------------------------------------------
-- 3. rbac_role_permissions (250 registros)
-- -----------------------------------------------
INSERT IGNORE INTO `rbac_role_permissions` (`role_code`, `permission_key`, `allowed`, `source`, `created_at`, `updated_at`) VALUES
-- Rol A (Administrador) - Acceso total
('A','admin.auditoria.ver',1,'phase1_seed',NOW(),NOW()),
('A','admin.miembros.gestionar',1,'phase1_seed',NOW(),NOW()),
('A','admin.panel.acceso',1,'phase1_seed',NOW(),NOW()),
('A','admin.permisos.gestionar',1,'phase1_seed',NOW(),NOW()),
('A','admin.proyectos.gestionar',1,'phase1_seed',NOW(),NOW()),
('A','admin.usuarios.gestionar',1,'phase1_seed',NOW(),NOW()),
('A','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.cnc.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.cnp.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.contratos.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.control_cambios.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.listado_actividades.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.paquetes_contratacion.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.pdc.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.profesionales.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.programa_general_actualizar.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.programa_general.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.programacion_intermedia.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.programacion_semanal.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('A','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('A','lps.subcontratistas.editar',1,'phase1_seed',NOW(),NOW()),
('A','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('A','notificaciones.admin_seguridad',1,'phase1_seed',NOW(),NOW()),
('A','notificaciones.cic_especialidad',1,'phase1_seed',NOW(),NOW()),
('A','notificaciones.ejecutivas',1,'phase1_seed',NOW(),NOW()),
('A','notificaciones.gestion_pdc_contratos',1,'phase1_seed',NOW(),NOW()),
('A','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('A','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('A','lps.semana.crear',1,'phase1_seed',NOW(),NOW()),
('A','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol C (Subcontratista) - Mínimo
('C','notificaciones.cic_especialidad',1,'phase1_seed',NOW(),NOW()),
('C','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('C','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol D (Director Funcional) - Todo LPS + notificaciones
('D','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.cnc.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.cnp.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.contratos.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.control_cambios.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.listado_actividades.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.paquetes_contratacion.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.pdc.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.profesionales.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.programa_general_actualizar.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.programa_general.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.programacion_intermedia.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.programacion_semanal.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('D','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('D','lps.subcontratistas.editar',1,'phase1_seed',NOW(),NOW()),
('D','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('D','notificaciones.cic_especialidad',1,'phase1_seed',NOW(),NOW()),
('D','notificaciones.ejecutivas',1,'phase1_seed',NOW(),NOW()),
('D','notificaciones.gestion_pdc_contratos',1,'phase1_seed',NOW(),NOW()),
('D','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('D','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('D','lps.semana.crear',1,'phase1_seed',NOW(),NOW()),
('D','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol DCV (Profesional DCV) - Edición selectiva
('DCV','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.cnc.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.cnp.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.control_cambios.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programa_general_actualizar.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programa_general.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programacion_intermedia.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programacion_semanal.editar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('DCV','notificaciones.gestion_pdc_contratos',1,'phase1_seed',NOW(),NOW()),
('DCV','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('DCV','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('DCV','lps.semana.crear',1,'phase1_seed',NOW(),NOW()),
('DCV','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol G (Ambiental) - Solo CIC
('G','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('G','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('G','notificaciones.cic_especialidad',1,'phase1_seed',NOW(),NOW()),
('G','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('G','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol OT (Oficina Técnica) - Lectura mixta
('OT','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.contratos.editar',1,'phase1_seed',NOW(),NOW()),
('OT','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.listado_actividades.editar',1,'phase1_seed',NOW(),NOW()),
('OT','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.pdc.editar',1,'phase1_seed',NOW(),NOW()),
('OT','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('OT','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('OT','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('OT','notificaciones.gestion_pdc_contratos',1,'phase1_seed',NOW(),NOW()),
('OT','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('OT','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('OT','lps.semana.crear',1,'phase1_seed',NOW(),NOW()),
('OT','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol P (Legacy alias de D) - Permisos completos LPS
('P','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.cnc.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.cnp.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.contratos.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.control_cambios.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.listado_actividades.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.paquetes_contratacion.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.pdc.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.profesionales.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.programa_general_actualizar.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.programa_general.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.programacion_intermedia.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.programacion_semanal.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('P','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('P','lps.subcontratistas.editar',1,'phase1_seed',NOW(),NOW()),
('P','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('P','notificaciones.cic_especialidad',1,'phase1_seed',NOW(),NOW()),
('P','notificaciones.ejecutivas',1,'phase1_seed',NOW(),NOW()),
('P','notificaciones.gestion_pdc_contratos',1,'phase1_seed',NOW(),NOW()),
('P','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('P','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('P','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol R (Residente de Obra) - Edición LPS, lectura PDC/contratos
('R','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.cnc.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.cnp.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.control_cambios.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.programa_general_actualizar.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.programa_general.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.programacion_intermedia.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.programacion_semanal.editar',1,'phase1_seed',NOW(),NOW()),
('R','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('R','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('R','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('R','notificaciones.gestion_pdc_contratos',1,'phase1_seed',NOW(),NOW()),
('R','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('R','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('R','lps.semana.crear',1,'phase1_seed',NOW(),NOW()),
('R','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol S (SST) - Solo CIC
('S','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('S','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('S','notificaciones.cic_especialidad',1,'phase1_seed',NOW(),NOW()),
('S','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('S','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol SG (SST + Ambiental) - Solo CIC
('SG','lps.cic.editar',1,'phase1_seed',NOW(),NOW()),
('SG','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('SG','notificaciones.cic_especialidad',1,'phase1_seed',NOW(),NOW()),
('SG','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('SG','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol U (Legacy alias de V) - Solo lectura
('U','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('U','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('U','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('U','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('U','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('U','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW()),
-- Rol V (Visualizador) - Solo lectura
('V','lps.cic.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.cnc.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.cnp.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.contratos.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.control_cambios.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.indicadores.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.listado_actividades.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.paquetes_contratacion.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.pdc.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.profesionales.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.programa_general_actualizar.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.programa_general.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.programacion_intermedia.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.programacion_semanal.ver',1,'phase1_seed',NOW(),NOW()),
('V','lps.reportes.generar',1,'phase1_seed',NOW(),NOW()),
('V','lps.subcontratistas.ver',1,'phase1_seed',NOW(),NOW()),
('V','notificaciones.lps_operativas',1,'phase1_seed',NOW(),NOW()),
('V','notificaciones.preferencias_personales',1,'phase1_seed',NOW(),NOW()),
('V','notificaciones.resumen_semanal',1,'phase1_seed',NOW(),NOW());

-- -----------------------------------------------
-- 4. notification_types (7 tipos)
-- -----------------------------------------------
INSERT IGNORE INTO `notification_types` (`notification_code`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES
('admin_seguridad','Administracion y Seguridad','Alertas de seguridad y gestion administrativa',1,NOW(),NOW()),
('cic_especialidad','CIC por Especialidad','Alertas CIC segmentadas por especialidad',1,NOW(),NOW()),
('ejecutivas','Ejecutivas','Alertas para seguimiento ejecutivo',1,NOW(),NOW()),
('gestion_pdc_contratos','Gestion PDC y Contratos','Alertas de gestion sobre PDC y contratos',1,NOW(),NOW()),
('lps_operativas','LPS Operativas','Alertas operativas de modulos LPS',1,NOW(),NOW()),
('preferencias_personales','Preferencias Personales','Configuracion de preferencias de notificacion',1,NOW(),NOW()),
('resumen_semanal','Resumen Semanal','Consolidado semanal por rol',1,NOW(),NOW());

-- -----------------------------------------------
-- 5. event_dictionary (56 eventos)
-- -----------------------------------------------
INSERT IGNORE INTO `event_dictionary` (`event_code`, `event_action`, `modulo_legacy`, `accion_legacy`, `severity`, `auditable`, `notification_code`, `description`, `created_at`, `updated_at`) VALUES
('lps.cic','modificar','ProgramacionSemanal','MODIFICAR_CIC','info',1,'cic_especialidad','Actualizacion de CIC',NOW(),NOW()),
('lps.cnc','modificar','ProgramacionSemanal','MODIFICAR_CNC','info',1,'lps_operativas','Actualizacion de CNC',NOW(),NOW()),
('lps.cnp','modificar','ProgramacionSemanal','MODIFICAR_CNP','info',1,'lps_operativas','Actualizacion de CNP',NOW(),NOW()),
('lps.contratos','crear_dias_proceso','Contratos','CREAR_DIAS_PROCESO','info',1,'gestion_pdc_contratos','Creacion de dias de proceso de contrato',NOW(),NOW()),
('lps.contratos','modificar','Contratos','MODIFICAR','info',1,'gestion_pdc_contratos','Actualizacion de contratos',NOW(),NOW()),
('lps.control_cambios','crear','ControlCambios','CREAR','info',1,'lps_operativas','Creacion de control de cambios',NOW(),NOW()),
('lps.control_cambios','eliminar','ControlCambios','ELIMINAR','warning',1,'lps_operativas','Eliminacion de control de cambios',NOW(),NOW()),
('lps.control_cambios','eliminar_semana','ControlCambios','ELIMINAR_SEMANA','warning',1,'lps_operativas','Eliminacion de semana',NOW(),NOW()),
('lps.control_cambios','modificar','ControlCambios','MODIFICAR','info',1,'lps_operativas','Actualizacion de control de cambios',NOW(),NOW()),
('lps.control_cambios','nueva_semana','ControlCambios','NUEVA_SEMANA','info',1,'lps_operativas','Creacion de nueva semana',NOW(),NOW()),
('lps.listado_actividades','crear','ListadoActividades','CREAR','info',1,'lps_operativas','Creacion de actividad en listado',NOW(),NOW()),
('lps.listado_actividades','eliminar','ListadoActividades','ELIMINAR','warning',1,'lps_operativas','Eliminacion de actividad en listado',NOW(),NOW()),
('lps.listado_actividades','importar','ListadoActividades','IMPORTAR','info',1,'lps_operativas','Importacion masiva de actividades',NOW(),NOW()),
('lps.listado_actividades','modificar','ListadoActividades','MODIFICAR','info',1,'lps_operativas','Actualizacion de actividad en listado',NOW(),NOW()),
('lps.pdc','adjudicar','PDC','ADJUDICAR_PDC','info',1,'gestion_pdc_contratos','Adjudicacion de PDC',NOW(),NOW()),
('lps.pdc','crear','PDC','CREAR_ACTIVIDAD','info',1,'gestion_pdc_contratos','Creacion de actividad PDC',NOW(),NOW()),
('lps.pdc','eliminar','PDC','ELIMINAR_ACTIVIDAD','warning',1,'gestion_pdc_contratos','Eliminacion de actividad PDC',NOW(),NOW()),
('lps.pdc','modificar','PDC','MODIFICAR_ACTIVIDAD','info',1,'gestion_pdc_contratos','Actualizacion de actividad PDC',NOW(),NOW()),
('lps.pdc','modificar_celda','PDC','MODIFICAR_CELDA','info',1,'gestion_pdc_contratos','Actualizacion de celda individual PDC',NOW(),NOW()),
('lps.programacion_intermedia','modificar','ProgramacionIntermedia','MODIFICAR','info',1,'lps_operativas','Actualizacion de programacion intermedia',NOW(),NOW()),
('lps.programacion_intermedia','shared_restriction_apply','ProgramacionIntermedia','SHARED_RESTRICTION_APPLY','info',1,'lps_operativas','Aplicacion de restricciones compartidas',NOW(),NOW()),
('lps.programacion_semanal','modificar','ProgramacionSemanal','MODIFICAR','info',1,'lps_operativas','Actualizacion de programacion semanal',NOW(),NOW()),
('notificaciones.envio','enviada','Notificaciones','ENVIADA','info',1,NULL,'Notificacion enviada',NOW(),NOW()),
('notificaciones.envio','fallida','Notificaciones','FALLIDA','warning',1,'admin_seguridad','Notificacion fallida',NOW(),NOW()),
('notificaciones.planeadas','admin_seguridad','Notificaciones','PLAN_ADMIN_SEGURIDAD','warning',1,'admin_seguridad','Configuracion de alertas admin y seguridad',NOW(),NOW()),
('notificaciones.planeadas','cic_especialidad','Notificaciones','PLAN_CIC_ESPECIALIDAD','info',1,'cic_especialidad','Configuracion de alertas CIC por especialidad',NOW(),NOW()),
('notificaciones.planeadas','ejecutivas','Notificaciones','PLAN_EJECUTIVAS','info',1,'ejecutivas','Configuracion de alertas ejecutivas',NOW(),NOW()),
('notificaciones.planeadas','gestion_pdc_contratos','Notificaciones','PLAN_GESTION_PDC_CONTRATOS','info',1,'gestion_pdc_contratos','Configuracion de alertas de gestion PDC y contratos',NOW(),NOW()),
('notificaciones.planeadas','lps_operativas','Notificaciones','PLAN_LPS_OPERATIVAS','info',1,'lps_operativas','Configuracion de alertas operativas LPS',NOW(),NOW()),
('notificaciones.planeadas','preferencias_personales','Notificaciones','PLAN_PREFERENCIAS_PERSONALES','info',1,'preferencias_personales','Configuracion de preferencias personales',NOW(),NOW()),
('notificaciones.planeadas','resumen_semanal','Notificaciones','PLAN_RESUMEN_SEMANAL','info',1,'resumen_semanal','Configuracion de resumen semanal',NOW(),NOW()),
('proyecto.lifecycle','backup','Proyectos','BACKUP','info',1,'admin_seguridad','Generacion de respaldo de proyecto',NOW(),NOW()),
('proyecto.lifecycle','crear','Proyectos','CREAR','info',1,'admin_seguridad','Creacion de proyecto',NOW(),NOW()),
('proyecto.lifecycle','eliminar','Proyectos','ELIMINAR','warning',1,'admin_seguridad','Eliminacion de proyecto',NOW(),NOW()),
('proyecto.lifecycle','estado','Proyectos','ESTADO','info',1,NULL,'Cambio de estado del proyecto',NOW(),NOW()),
('proyecto.lifecycle','modificar','Proyectos','MODIFICAR','info',1,'admin_seguridad','Actualizacion de proyecto',NOW(),NOW()),
('rbac.miembro_proyecto','actualizar_rol','Miembros','MODIFICAR','info',1,'admin_seguridad','Cambio de rol de miembro',NOW(),NOW()),
('rbac.miembro_proyecto','agregar','Miembros','CREAR','info',1,'admin_seguridad','Asignacion de miembro a proyecto',NOW(),NOW()),
('rbac.miembro_proyecto','remover','Miembros','ELIMINAR','warning',1,'admin_seguridad','Remocion de miembro de proyecto',NOW(),NOW()),
('rbac.permisos','actualizar_rol','Seguridad','RBAC_ACTUALIZAR_ROL','warning',1,'admin_seguridad','Actualizacion de matriz de permisos',NOW(),NOW()),
('rbac.permisos','migracion_p_a_d','Sistema','MIGRACION_P_A_D','warning',1,'admin_seguridad','Migracion de codigo legacy P a D',NOW(),NOW()),
('rbac.usuario','crear','Usuarios','CREAR','info',1,'admin_seguridad','Creacion de usuario',NOW(),NOW()),
('rbac.usuario','eliminar','Usuarios','ELIMINAR','warning',1,'admin_seguridad','Eliminacion de usuario',NOW(),NOW()),
('rbac.usuario','modificar','Usuarios','MODIFICAR','info',1,'admin_seguridad','Actualizacion de usuario',NOW(),NOW()),
('seguridad.auth','login_exitoso','Seguridad','LOGIN','info',1,'admin_seguridad','Inicio de sesion exitoso',NOW(),NOW()),
('seguridad.auth','login_fallido','Seguridad','LOGIN_FALLIDO','warning',1,'admin_seguridad','Intento de autenticacion fallido',NOW(),NOW()),
('seguridad.auth','logout','Seguridad','LOGOUT','info',1,NULL,'Cierre de sesion',NOW(),NOW()),
('seguridad.autorizacion','denegada','Seguridad','AUTORIZACION_DENEGADA','warning',1,'admin_seguridad','Intento de acceso denegado por RBAC',NOW(),NOW()),
('seguridad.proyecto','acceso','Login','ACCESO_PROYECTO','info',1,NULL,'Acceso a proyecto',NOW(),NOW()),
('sistema.procesos','actualizar_pdc_nueva_semana','Sistema','PDC_ACTUALIZAR','info',1,'gestion_pdc_contratos','Actualizacion de PDC para nueva semana',NOW(),NOW()),
('sistema.procesos','autoprogramar','Sistema','AUTOPROGRAMAR','info',1,'lps_operativas','Autoprogramacion de actividades',NOW(),NOW()),
('sistema.procesos','limpieza','Sistema','LIMPIEZA','warning',1,'admin_seguridad','Limpieza tecnica de tablas huerfanas',NOW(),NOW()),
('sistema.reportes','generar_curva_s','Sistema','GENERAR_CURVA_S','info',1,'ejecutivas','Generacion de Curva S',NOW(),NOW()),
('sistema.reportes','generar_curva_s_pdc','Sistema','GENERAR_CURVA_S_PDC','info',1,'ejecutivas','Generacion de Curva S PDC',NOW(),NOW()),
('sistema.reportes','generar_curva_sb','Sistema','GENERAR_CURVA_SB','info',1,'ejecutivas','Generacion de Curva SB',NOW(),NOW()),
('sistema.reportes','generar_reporte_gral','Sistema','GENERAR_REPORTE_GRAL','info',1,'ejecutivas','Generacion de reporte general',NOW(),NOW()),
('sistema.reportes','generar_reporte_pdc','Sistema','GENERAR_REPORTE_PDC','info',1,'ejecutivas','Generacion de reporte PDC',NOW(),NOW()),
('sistema.reportes','generar_restricciones_gral','Sistema','GENERAR_RESTRICCIONES_GRAL','info',1,'ejecutivas','Generacion de reporte general de restricciones',NOW(),NOW());

-- -----------------------------------------------
-- 6. general_feature_flags (1 flag)
-- -----------------------------------------------
INSERT IGNORE INTO `general_feature_flags` (`flag_key`, `flag_value`, `description`, `updated_by`, `updated_at`) VALUES
('console_logs_enabled',0,'Controla la visualizacion global de console.log en el frontend.','migration',NOW());

-- -----------------------------------------------
-- 7. role_intelligence (22 registros)
-- -----------------------------------------------
INSERT IGNORE INTO `role_intelligence` (`cargo_title`, `suggested_role`, `updated_at`) VALUES
('director proyecto','A',NOW()),
('director obra','D',NOW()),
('coordinador obra','D',NOW()),
('coordinador diseos','D',NOW()),
('coordinador planeacion','D',NOW()),
('residente obra','R',NOW()),
('auxiliar ingenieria','R',NOW()),
('residente programacion','R',NOW()),
('residente interventoria','V',NOW()),
('residente acabados','R',NOW()),
('oficina tecnica compras','OT',NOW()),
('profesional compras aprovisionamiento','OT',NOW()),
('residente control costos','OT',NOW()),
('profesional ambiental','G',NOW()),
('profesional sst','S',NOW()),
('profesional sst ambiental','SG',NOW()),
('coordinador calidad','V',NOW()),
('profesional bim','V',NOW()),
('profesional dcv','DCV',NOW()),
('profesional pi','V',NOW()),
('subcontratista','C',NOW()),
('invitado','V',NOW());

-- -----------------------------------------------
-- 8. role_notification_defaults (49 registros)
-- -----------------------------------------------
INSERT IGNORE INTO `role_notification_defaults` (`role_code`, `notification_code`, `enabled`, `created_at`, `updated_at`) VALUES
('A','admin_seguridad',1,NOW(),NOW()),
('A','cic_especialidad',1,NOW(),NOW()),
('A','ejecutivas',1,NOW(),NOW()),
('A','gestion_pdc_contratos',1,NOW(),NOW()),
('A','lps_operativas',1,NOW(),NOW()),
('A','preferencias_personales',1,NOW(),NOW()),
('A','resumen_semanal',1,NOW(),NOW()),
('C','cic_especialidad',1,NOW(),NOW()),
('C','preferencias_personales',1,NOW(),NOW()),
('C','resumen_semanal',1,NOW(),NOW()),
('D','cic_especialidad',1,NOW(),NOW()),
('D','ejecutivas',1,NOW(),NOW()),
('D','gestion_pdc_contratos',1,NOW(),NOW()),
('D','lps_operativas',1,NOW(),NOW()),
('D','preferencias_personales',1,NOW(),NOW()),
('D','resumen_semanal',1,NOW(),NOW()),
('DCV','gestion_pdc_contratos',1,NOW(),NOW()),
('DCV','lps_operativas',1,NOW(),NOW()),
('DCV','preferencias_personales',1,NOW(),NOW()),
('DCV','resumen_semanal',1,NOW(),NOW()),
('G','cic_especialidad',1,NOW(),NOW()),
('G','preferencias_personales',1,NOW(),NOW()),
('G','resumen_semanal',1,NOW(),NOW()),
('OT','gestion_pdc_contratos',1,NOW(),NOW()),
('OT','lps_operativas',1,NOW(),NOW()),
('OT','preferencias_personales',1,NOW(),NOW()),
('OT','resumen_semanal',1,NOW(),NOW()),
('P','cic_especialidad',1,NOW(),NOW()),
('P','ejecutivas',1,NOW(),NOW()),
('P','gestion_pdc_contratos',1,NOW(),NOW()),
('P','lps_operativas',1,NOW(),NOW()),
('P','preferencias_personales',1,NOW(),NOW()),
('P','resumen_semanal',1,NOW(),NOW()),
('R','gestion_pdc_contratos',1,NOW(),NOW()),
('R','lps_operativas',1,NOW(),NOW()),
('R','preferencias_personales',1,NOW(),NOW()),
('R','resumen_semanal',1,NOW(),NOW()),
('S','cic_especialidad',1,NOW(),NOW()),
('S','preferencias_personales',1,NOW(),NOW()),
('S','resumen_semanal',1,NOW(),NOW()),
('SG','cic_especialidad',1,NOW(),NOW()),
('SG','preferencias_personales',1,NOW(),NOW()),
('SG','resumen_semanal',1,NOW(),NOW()),
('U','lps_operativas',1,NOW(),NOW()),
('U','preferencias_personales',1,NOW(),NOW()),
('U','resumen_semanal',1,NOW(),NOW()),
('V','lps_operativas',1,NOW(),NOW()),
('V','preferencias_personales',1,NOW(),NOW()),
('V','resumen_semanal',1,NOW(),NOW());

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================================
-- FIN Script 003 — ~400 registros de seed data, 100% INSERT IGNORE
-- ============================================================================
