CREATE TABLE IF NOT EXISTS `general_decision_log` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `proyecto_id` VARCHAR(50) NOT NULL,
    `semana_objetivo` INT NOT NULL,
    `actividad_consecutivo` VARCHAR(20) NOT NULL,
    `actividad_nombre` TEXT NOT NULL,
    `actividad_tokens` JSON NOT NULL,
    `actividad_posicion_pg` INT NOT NULL,
    `actividad_vecinos` JSON NULL,
    `actividad_capitulo` VARCHAR(100) NULL,
    `engine_usado` VARCHAR(30) NOT NULL,
    `proceso_sugerido` VARCHAR(200) NULL,
    `confianza` DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    `regla_aplicada` VARCHAR(50) NULL,
    `candidatos_alternativos` JSON NULL,
    `explicacion` TEXT NULL,
    `decision_usuario` ENUM('accept','correct','skip','manual') NOT NULL,
    `proceso_final` VARCHAR(200) NOT NULL,
    `proceso_final_id` INT NULL,
    `usuario_id` VARCHAR(20) NULL,
    `timestamp_utc` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_proyecto` (`proyecto_id`),
    INDEX `idx_decision` (`decision_usuario`),
    INDEX `idx_engine` (`engine_usado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;