-- Migration: Seed V1.0 families, test contract, and contract options
-- Generated by seed_v1_0_migration.py
-- Purpose: Fix e2e test failures (Da Porto feedback model, contract options)

-- ============================================================
-- PART 1: Insert missing families from V1.0
-- ============================================================
INSERT INTO `general_pdc_familias`
  (`codigo`, `nombre`, `categoria`, `orden`, `siempre_revision`, `activa`)
VALUES
  ('PROV_ELECTRICAS_CAMPAMENTO', 'Provisionales eléctricas de campamento', 'Preliminares', 900, 1, 0),
  ('PROV_HIDROSANITARIAS', 'Provisionales hidrosanitarias', 'Preliminares', 901, 1, 0),
  ('CAMPAMENTO_OBRA', 'Campamento de obra', 'Preliminares', 902, 1, 0),
  ('TRANSPORTE_PERSONAL_CAMIONETA', 'Transporte de personal y camioneta', 'Preliminares', 903, 1, 0),
  ('PMT_DISENO_IMPLEMENTACION', 'Plan de manejo de tránsito PMT', 'Preliminares', 904, 1, 0),
  ('ACTAS_VECINDAD', 'Actas de vecindad', 'Preliminares', 905, 1, 0),
  ('VIGILANCIA_OBRA', 'Vigilancia de obra', 'Preliminares', 906, 1, 0),
  ('CERRAMIENTOS_PROVISIONALES_SUPERBOARD', 'Cerramientos provisionales en superboard', 'Preliminares', 907, 1, 0),
  ('CERRAMIENTO_LAMINA_METALICO', 'Cerramiento en lámina metálico', 'Preliminares', 908, 1, 0),
  ('CERRAMIENTO_LONA_MALLA', 'Cerramiento en lona o malla eslabonada', 'Preliminares', 909, 1, 0),
  ('ASEO_FINAL_ENTREGA', 'Aseo final y entrega', 'Preliminares', 910, 1, 0),
  ('DESCAPOTE', 'Descapote', 'Movimiento de tierras', 911, 0, 0),
  ('RETIROS_DEMOLICIONES', 'Retiros y demoliciones', 'Demoliciones', 912, 1, 0),
  ('DEMOLICIONES_ESPECIALES', 'Demoliciones especiales', 'Demoliciones', 913, 1, 0),
  ('EXCAVACIONES_LLENOS', 'Excavaciones y llenos', 'Movimiento de tierras', 914, 1, 0),
  ('BOTADA_RETIRO_ESCOMBROS', 'Botada, retiro y disposición de escombros', 'Movimiento de tierras', 915, 1, 0),
  ('RELLENOS_SUBBASE', 'Rellenos y subbase granular', 'Movimiento de tierras', 916, 1, 0),
  ('PILOTES', 'Pilotes hincados / tornillo / inclusión rígida', 'Fundaciones', 917, 1, 0),
  ('DESCABEZADA_PREHUECO_PILOTES', 'Descabezada y prehueco de pilotes', 'Fundaciones', 918, 0, 0),
  ('FOSO_ASCENSOR', 'Foso de ascensor', 'Fundaciones', 919, 0, 0),
  ('MUROS_CONTENCION_CONCRETO', 'Muros de contención en concreto', 'Estructura', 920, 0, 0),
  ('CONCRETO_POBRE', 'Concreto pobre', 'Estructura', 921, 1, 0),
  ('CONCRETO_PILOTES', 'Concreto para pilotes', 'Fundaciones', 922, 1, 0),
  ('SUMINISTRO_CONCRETO', 'Suministro de concreto', 'Estructura', 923, 1, 0),
  ('ACERO_REFUERZO', 'Acero de refuerzo', 'Estructura', 924, 1, 0),
  ('MALLA_GRAFIL_REFUERZO', 'Malla y grafil de refuerzo', 'Estructura', 925, 1, 0),
  ('ANCLAJES_EPOXICOS', 'Anclajes epóxicos', 'Estructura', 926, 1, 0),
  ('GROUTING', 'Grouting', 'Estructura', 927, 1, 0),
  ('PLACA_CIMENTACION', 'Placa de cimentación', 'Estructura', 928, 0, 0),
  ('PLACAS_ENTREPISO', 'Placas de entrepiso / placas macizas', 'Estructura', 929, 0, 0),
  ('COLUMNAS_CONCRETO', 'Columnas en concreto', 'Estructura', 930, 0, 0),
  ('RAMPAS_CONCRETO', 'Rampas en concreto', 'Estructura', 931, 0, 0),
  ('ESCALERAS_CONCRETO', 'Escaleras en concreto', 'Estructura', 932, 0, 0),
  ('BOMBEO_CONCRETO', 'Servicio de bombeo de concreto', 'Estructura', 933, 1, 0),
  ('JUNTAS_DILATACIONES_PISO', 'Juntas, cortes y sellos en piso', 'Acabados pisos', 934, 1, 0),
  ('ESTRUCTURA_METALICA', 'Estructura metálica', 'Metálica', 935, 1, 0),
  ('METALDECK', 'Metaldeck', 'Metálica', 936, 1, 0),
  ('BARANDAS_PASAMANOS_METALICOS', 'Barandas y pasamanos metálicos', 'Metálica', 937, 1, 0),
  ('CUBIERTAS_MARQUESINAS', 'Cubiertas, paneles y marquesinas', 'Cubiertas', 938, 1, 0),
  ('PERGOLA_POLICARBONATO', 'Pérgola / cubierta en policarbonato', 'Cubiertas', 939, 1, 0),
  ('FACHADA_PERSIANA_LUVERS', 'Fachada tipo persiana / luvers', 'Fachadas', 940, 1, 0),
  ('VENTANERIA_PUERTAS_VIDRIERAS', 'Ventanería y puertas vidrieras', 'Fachadas y carpinterías', 941, 1, 0),
  ('REJILLAS_VENTILACION', 'Rejillas y elementos de ventilación', 'Fachadas y carpinterías', 942, 1, 0),
  ('PUERTAS_METALICAS_CORTAFUEGO', 'Puertas metálicas y cortafuego', 'Carpinterías', 943, 1, 0),
  ('MAMPOSTERIA_BLOQUE', 'Mampostería en bloque', 'Mampostería', 944, 1, 0),
  ('BLOQUE_CONCRETO_ARCILLA', 'Bloque concreto / arcilla', 'Mampostería', 945, 1, 0),
  ('BLOQUE_FACHADA_CATALAN', 'Bloque fachada catalán', 'Mampostería', 946, 1, 0),
  ('MUROS_LIVIANOS_CIELOS', 'Muros livianos y cielos', 'Muros livianos', 947, 1, 0),
  ('MURO_FIBROCEMENTO', 'Muro liviano en fibrocemento', 'Muros livianos', 948, 1, 0),
  ('DINTEL_VIGA_CINTA_BORDILLOS', 'Dinteles, viga cinta, bordillos y sillares', 'Obra gris', 949, 0, 0),
  ('REVOQUE_PANETE', 'Revoque / pañete', 'Acabados muros', 950, 1, 0),
  ('REVOQUE_FACHADA', 'Revoque fachada', 'Acabados fachada', 951, 1, 0),
  ('PINTURA_MUROS_CIELOS', 'Pintura sobre muros y cielos', 'Pintura', 952, 1, 0),
  ('ESTUCO_PINTURA_INTERIORES', 'Estuco y pintura interiores', 'Pintura', 953, 1, 0),
  ('CIELO_DRYWALL_SUPERBOARD', 'Cielo raso en drywall / superboard', 'Cielos', 954, 1, 0),
  ('CIELO_MODULAR_TILE_OWA', 'Cielo modular OWA / tile lay-in', 'Cielos', 955, 1, 0),
  ('CIELO_HUNTER_DOUGLAS', 'Cielo Hunter Douglas baffle / R84', 'Cielos', 956, 1, 0),
  ('TRATAMIENTO_ACUSTICO_BLACK_THEATER', 'Tratamiento acústico black theater', 'Cielos', 957, 1, 0),
  ('PISO_GRANO_ROCA', 'Piso en grano / roca', 'Pisos', 958, 1, 0),
  ('PISO_CONCRETO_PULIDO', 'Piso concreto pulido / endurecido', 'Pisos', 959, 1, 0),
  ('PISO_BALDOSA_PORCELANATO', 'Piso en baldosa / porcelanato', 'Pisos', 960, 1, 0),
  ('PISO_LAMINADO_VINILO', 'Piso laminado / vinilo', 'Pisos', 961, 1, 0),
  ('PISO_GRES', 'Piso gres', 'Pisos', 962, 1, 0),
  ('MORTEROS_AFINADOS_PISO', 'Morteros y afinados de piso', 'Pisos', 963, 1, 0),
  ('IMPERMEABILIZACION_CUBIERTAS', 'Impermeabilización cubiertas y terrazas', 'Impermeabilización', 964, 1, 0),
  ('IMPERMEABILIZACION_BANOS_BALCONES', 'Impermeabilización baños y balcones', 'Impermeabilización', 965, 1, 0),
  ('IMPERMEABILIZACION_FOSO_MUROS', 'Impermeabilización foso ascensor / muros', 'Impermeabilización', 966, 1, 0),
  ('EMBOQUILLE_SILICONA_ZOCALOS', 'Emboquille, silicona y zócalos', 'Acabados', 967, 1, 0),
  ('PUERTAS_MADERA_CORREDIZAS', 'Puertas de madera y corredizas', 'Carpintería madera', 968, 1, 0),
  ('CERRADURAS_HERRAJES', 'Cerraduras y herrajes', 'Carpintería madera', 969, 1, 0),
  ('MUEBLES_CHECKIN_COUNTERS', 'Muebles check-in / counters', 'Carpintería y mobiliario', 970, 1, 0),
  ('CARPINTERIA_MADERA_CLOSETS', 'Carpintería madera closets / vestier', 'Carpintería madera', 971, 1, 0),
  ('MUEBLES_COCINA_BANO', 'Muebles de cocina y baño', 'Carpintería madera', 972, 1, 0),
  ('MESONES_COCINA_BANO', 'Mesones cocina / baño', 'Mesones y superficies', 973, 1, 0),
  ('APARATOS_SANITARIOS', 'Aparatos sanitarios', 'Hidrosanitario acabados', 974, 1, 0),
  ('GRIFERIAS_ACCESORIOS_BANO', 'Griferías y accesorios de baño', 'Hidrosanitario acabados', 975, 1, 0),
  ('DIVISIONES_CABINAS_BANO', 'Divisiones y cabinas de baño', 'Acabados baños', 976, 1, 0),
  ('ESPEJOS', 'Espejos', 'Acabados baños', 977, 1, 0),
  ('LAVADEROS_POZUELOS', 'Lavaderos, lavaescobas y pozuelos', 'Acabados baños/cocinas', 978, 1, 0),
  ('ELECTRODOMESTICOS_APTOS', 'Electrodomésticos apartamentos', 'Dotaciones', 979, 1, 0),
  ('SENALIZACION_NOMENCLATURA', 'Señalización y nomenclatura', 'Señalización', 980, 1, 0),
  ('DEMARCACION_PARQUEADEROS', 'Demarcación de parqueaderos', 'Urbanismo', 981, 1, 0),
  ('URBANISMO_ANDENES_PAVIMENTOS', 'Urbanismo, andenes y pavimentos', 'Urbanismo', 982, 1, 0),
  ('JARDINERIA_PAISAJISMO', 'Jardinería y paisajismo', 'Urbanismo', 983, 1, 0),
  ('INSTALACIONES_ELECTRICAS', 'Instalaciones eléctricas', 'Eléctrico', 984, 1, 0),
  ('TABLEROS_APARATOS_ELECTRICOS', 'Tableros y aparatos eléctricos', 'Eléctrico', 985, 1, 0),
  ('ILUMINACION_GENERAL', 'Iluminación general', 'Eléctrico', 986, 1, 0),
  ('ILUMINACION_EMERGENCIA', 'Iluminación de emergencia', 'Eléctrico', 987, 1, 0),
  ('ACOMETIDA_SUBESTACION', 'Acometida subestación', 'Eléctrico', 988, 1, 0),
  ('APANTALLAMIENTO_PUESTA_TIERRA', 'Apantallamiento y puesta a tierra', 'Eléctrico', 989, 1, 0),
  ('PLANTA_EMERGENCIA_BATERIAS', 'Planta de emergencia / generador / banco de baterías', 'Eléctrico equipos', 990, 1, 0),
  ('HIDROSANITARIAS', 'Instalaciones hidrosanitarias', 'Hidrosanitario', 991, 1, 0),
  ('TUBERIAS_ACCESORIOS_HIDROSANITARIOS', 'Tuberías y accesorios hidrosanitarios', 'Hidrosanitario', 992, 1, 0),
  ('EQUIPO_PRESION_BOMBAS_TANQUES', 'Equipo de presión, bombas y tanques', 'Hidrosanitario equipos', 993, 1, 0),
  ('RED_CONTRA_INCENDIO_RCI', 'Red contra incendio RCI', 'PCI', 994, 1, 0),
  ('GABINETES_TECNICOS_CONTADORES', 'Gabinetes técnicos y de contadores', 'Eléctrico equipos', 995, 1, 0),
  ('DETECCION_ALARMA_INCENDIO', 'Detección y alarma de incendio', 'PCI / Seguridad electrónica', 996, 1, 0),
  ('SEGURIDAD_CONTROL_ACCESO_INTRUSION', 'Seguridad y control / control de acceso / intrusión', 'Seguridad electrónica', 997, 1, 0),
  ('MONITOREO_CAMARAS_VIGILANCIA', 'Monitoreo de cámaras / vigilancia electrónica', 'Seguridad electrónica', 998, 1, 0),
  ('MONITOREO_INSTRUMENTACION_ALARMA', 'Monitoreo de instrumentación y alarma', 'Seguridad electrónica', 999, 1, 0),
  ('DATOS_RITEL_TELECOM', 'Sistema de datos, RITEL y telecomunicaciones', 'Telecomunicaciones', 1000, 1, 0),
  ('SONIDO_VIDEO_AYUDAS_VISUALES', 'Sonido, video y ayudas visuales', 'Audiovisual', 1001, 1, 0),
  ('HVAC_EXTRACCION_VENTILACION', 'HVAC, extracción y ventilación', 'Mecánico', 1002, 1, 0),
  ('SHUT_BASURAS', 'Shut de basuras', 'Equipos especiales', 1003, 1, 0),
  ('MALACATE_EQUIPOS_OBRA', 'Malacate y equipos de obra', 'Equipos de obra', 1004, 1, 0),
  ('ENSAYOS_CALIDAD_LAB', 'Ensayos de calidad / laboratorio de materiales', 'Calidad', 1005, 1, 0),
  ('SEGURIDAD_INDUSTRIAL_PMA', 'Seguridad industrial y plan de manejo ambiental', 'SST / Ambiental', 1006, 1, 0),
  ('FUNDICION_DOVELAS', 'Fundición de dovelas', 'Estructura', 1007, 1, 0),
  ('RECUBRIMIENTOS_ESPECIALES', 'Recubrimientos especiales y pintura industrial', 'Pintura', 1008, 1, 0),
  ('PUENTES_PASILLOS_PEATONALES', 'Puentes y pasillos peatonales', 'Urbanismo', 1009, 1, 0),
  ('REVOQUE_HUMEDO', 'Revoque Húmedo', 'ACABADOS', 1010, 0, 0),
  ('REVOQUE_SECO', 'Revoque Seco (Drywall)', 'ACABADOS', 1011, 0, 0),
  ('CABINAS_BANO', 'Cabinas de Baño', 'ACABADOS', 1012, 0, 0),
  ('PLANTA_ELECTRICA', 'Planta Eléctrica', 'EQUIPOS', 1013, 0, 0),
  ('MALACATE', 'Malacate', 'EQUIPOS', 1014, 0, 0),
  ('GRIFERIAS_INCRUSTACIONES', 'Griferías e Incrustaciones', 'INSTALACIONES', 1015, 0, 0),
  ('GEODREN', 'Geodren', 'INSTALACIONES', 1016, 0, 0),
  ('ASEO', 'Aseo', 'ACABADOS', 1017, 1, 0),
  ('BOTADA_ESCOMBROS', 'Botada de Escombros', 'PRELIMINARES', 1018, 1, 0),
  ('AMENIDADES_CUBIERTA', 'Amenidades de Cubierta', 'DOTACION', 1019, 1, 0)
ON DUPLICATE KEY UPDATE
  `nombre` = VALUES(`nombre`),
  `categoria` = VALUES(`categoria`),
  `siempre_revision` = VALUES(`siempre_revision`);

-- ============================================================
-- PART 2: Apply test contract (activa/siempre_revision flags)
-- ============================================================
-- 2a. Activate 7 activeListadoFamilies
UPDATE `general_pdc_familias` SET `activa` = 1 WHERE `codigo` IN ('REVOQUE_HUMEDO', 'REVOQUE_SECO', 'CABINAS_BANO', 'CARPINTERIA_METALICA', 'PLANTA_ELECTRICA', 'GRIFERIAS_INCRUSTACIONES', 'ASEO');

-- 2b. Deactivate 4 contractualOnlyFamilies
UPDATE `general_pdc_familias` SET `activa` = 0 WHERE `codigo` IN ('GEODREN', 'MALACATE', 'BOTADA_ESCOMBROS', 'AMENIDADES_CUBIERTA');

-- 2c. Set siempre_revision=1 for 5 reviewFamilies
UPDATE `general_pdc_familias` SET `siempre_revision` = 1 WHERE `codigo` IN ('CAMPAMENTO', 'RED_TELECOMUNICACIONES', 'ASEO', 'BOTADA_ESCOMBROS', 'AMENIDADES_CUBIERTA');

-- ============================================================
-- PART 3: Insert activity rules for families with 0 active rules
-- ============================================================
-- Rules for ENCHAPES
INSERT INTO `general_pdc_activity_rules`
  (`familia_id`, `patron_regex`, `modalidad_sugerida`, `confianza`, `prioridad`, `descripcion`, `activa`)
SELECT f.id, '/ENCHAPE|ENCHAPE MUROS|ENCHAPE PAREDES|MANO DE OBRA ENCHAPES/u', 'MO,S', 88, 100, 'Enchapes', 1
FROM `general_pdc_familias` f WHERE f.codigo = 'ENCHAPES';

-- ============================================================
-- PART 4: Insert contract options and items for test contract
-- ============================================================
-- SANITARIOS: Mano de Obra / INSTALACION APARATOS SANITARIOS
INSERT INTO `general_pdc_family_contract_options`
  (`familia_id`, `tipo_contrato`, `tipo_paquete`, `dias_elaboracion`, `dias_entrega`, `dias_recibo`, `dias_cuadros`, `dias_legalizacion`, `dias_fabricacion`, `dias_insumos`, `notas`, `activa`)
SELECT f.id, 1, 'Mano de Obra', 8, 10, 5, 10, 20, 10, 0, 'Contrato test contract para SANITARIOS', 1
FROM `general_pdc_familias` f WHERE f.codigo = 'SANITARIOS';

INSERT INTO `general_pdc_family_contract_option_items`
  (`option_id`, `tipo_contrato`, `tipo_paquete`, `paquete_nombre`, `cantidad_default`, `orden`)
SELECT o.id, o.tipo_contrato, o.tipo_paquete, 'INSTALACION APARATOS SANITARIOS', 1, 1
FROM `general_pdc_family_contract_options` o
JOIN `general_pdc_familias` f ON f.id = o.familia_id
WHERE f.codigo = 'SANITARIOS' AND o.tipo_paquete = 'Mano de Obra';

-- GRIFERIAS_INCRUSTACIONES: Orden de Compra / GRIFERIAS E INCRUSTACIONES
INSERT INTO `general_pdc_family_contract_options`
  (`familia_id`, `tipo_contrato`, `tipo_paquete`, `dias_elaboracion`, `dias_entrega`, `dias_recibo`, `dias_cuadros`, `dias_legalizacion`, `dias_fabricacion`, `dias_insumos`, `notas`, `activa`)
SELECT f.id, 5, 'Orden de Compra', 8, 10, 5, 10, 20, 10, 0, 'Contrato test contract para GRIFERIAS_INCRUSTACIONES', 1
FROM `general_pdc_familias` f WHERE f.codigo = 'GRIFERIAS_INCRUSTACIONES';

INSERT INTO `general_pdc_family_contract_option_items`
  (`option_id`, `tipo_contrato`, `tipo_paquete`, `paquete_nombre`, `cantidad_default`, `orden`)
SELECT o.id, o.tipo_contrato, o.tipo_paquete, 'GRIFERIAS E INCRUSTACIONES', 1, 1
FROM `general_pdc_family_contract_options` o
JOIN `general_pdc_familias` f ON f.id = o.familia_id
WHERE f.codigo = 'GRIFERIAS_INCRUSTACIONES' AND o.tipo_paquete = 'Orden de Compra';

-- PLANTA_ELECTRICA: Suministro / PLANTA ELECTRICA
INSERT INTO `general_pdc_family_contract_options`
  (`familia_id`, `tipo_contrato`, `tipo_paquete`, `dias_elaboracion`, `dias_entrega`, `dias_recibo`, `dias_cuadros`, `dias_legalizacion`, `dias_fabricacion`, `dias_insumos`, `notas`, `activa`)
SELECT f.id, 1, 'Suministro', 8, 10, 5, 10, 20, 10, 0, 'Contrato test contract para PLANTA_ELECTRICA', 1
FROM `general_pdc_familias` f WHERE f.codigo = 'PLANTA_ELECTRICA';

INSERT INTO `general_pdc_family_contract_option_items`
  (`option_id`, `tipo_contrato`, `tipo_paquete`, `paquete_nombre`, `cantidad_default`, `orden`)
SELECT o.id, o.tipo_contrato, o.tipo_paquete, 'PLANTA ELECTRICA', 1, 1
FROM `general_pdc_family_contract_options` o
JOIN `general_pdc_familias` f ON f.id = o.familia_id
WHERE f.codigo = 'PLANTA_ELECTRICA' AND o.tipo_paquete = 'Suministro';

-- CARPINTERIA_MADERA: Suministro / CARPINTERIA MADERA - FABRICACION Y SUMINISTRO
INSERT INTO `general_pdc_family_contract_options`
  (`familia_id`, `tipo_contrato`, `tipo_paquete`, `dias_elaboracion`, `dias_entrega`, `dias_recibo`, `dias_cuadros`, `dias_legalizacion`, `dias_fabricacion`, `dias_insumos`, `notas`, `activa`)
SELECT f.id, 1, 'Suministro', 8, 10, 5, 10, 20, 10, 0, 'Contrato test contract para CARPINTERIA_MADERA', 1
FROM `general_pdc_familias` f WHERE f.codigo = 'CARPINTERIA_MADERA';

INSERT INTO `general_pdc_family_contract_option_items`
  (`option_id`, `tipo_contrato`, `tipo_paquete`, `paquete_nombre`, `cantidad_default`, `orden`)
SELECT o.id, o.tipo_contrato, o.tipo_paquete, 'CARPINTERIA MADERA - FABRICACION Y SUMINISTRO', 1, 1
FROM `general_pdc_family_contract_options` o
JOIN `general_pdc_familias` f ON f.id = o.familia_id
WHERE f.codigo = 'CARPINTERIA_MADERA' AND o.tipo_paquete = 'Suministro';

-- CARPINTERIA_MADERA: Mano de Obra / CARPINTERIA MADERA - INSTALACION
INSERT INTO `general_pdc_family_contract_options`
  (`familia_id`, `tipo_contrato`, `tipo_paquete`, `dias_elaboracion`, `dias_entrega`, `dias_recibo`, `dias_cuadros`, `dias_legalizacion`, `dias_fabricacion`, `dias_insumos`, `notas`, `activa`)
SELECT f.id, 1, 'Mano de Obra', 8, 10, 5, 10, 20, 10, 0, 'Contrato test contract para CARPINTERIA_MADERA', 1
FROM `general_pdc_familias` f WHERE f.codigo = 'CARPINTERIA_MADERA';

INSERT INTO `general_pdc_family_contract_option_items`
  (`option_id`, `tipo_contrato`, `tipo_paquete`, `paquete_nombre`, `cantidad_default`, `orden`)
SELECT o.id, o.tipo_contrato, o.tipo_paquete, 'CARPINTERIA MADERA - INSTALACION', 1, 1
FROM `general_pdc_family_contract_options` o
JOIN `general_pdc_familias` f ON f.id = o.familia_id
WHERE f.codigo = 'CARPINTERIA_MADERA' AND o.tipo_paquete = 'Mano de Obra';

-- MALACATE: Equipos / MALACATE
INSERT INTO `general_pdc_family_contract_options`
  (`familia_id`, `tipo_contrato`, `tipo_paquete`, `dias_elaboracion`, `dias_entrega`, `dias_recibo`, `dias_cuadros`, `dias_legalizacion`, `dias_fabricacion`, `dias_insumos`, `notas`, `activa`)
SELECT f.id, 1, 'Equipos', 8, 10, 5, 10, 20, 10, 0, 'Contrato test contract para MALACATE', 1
FROM `general_pdc_familias` f WHERE f.codigo = 'MALACATE';

INSERT INTO `general_pdc_family_contract_option_items`
  (`option_id`, `tipo_contrato`, `tipo_paquete`, `paquete_nombre`, `cantidad_default`, `orden`)
SELECT o.id, o.tipo_contrato, o.tipo_paquete, 'MALACATE', 1, 1
FROM `general_pdc_family_contract_options` o
JOIN `general_pdc_familias` f ON f.id = o.familia_id
WHERE f.codigo = 'MALACATE' AND o.tipo_paquete = 'Equipos';
