-- ============================================================================
-- 20260630_global_tables_contract.sql
-- Contrato canonico de 20 tablas globales operativas con project_id.
-- Generado desde Docker local MySQL 8.0.40; estructura solamente, sin datos.
-- Ver documentacion: docs/global-tables-architecture.md
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `actividades` (
  `project_id` int NOT NULL,
  `Id` int NOT NULL,
  `codigo` int NOT NULL,
  `actividad` varchar(300) NOT NULL,
  `descripcionActividad` mediumtext,
  `actividadInicio` varchar(500) DEFAULT NULL,
  `nombreActividadInicio` varchar(500) DEFAULT NULL,
  `fechaInicio` date DEFAULT NULL,
  `tipoContrato` varchar(10) DEFAULT NULL,
  `semanaActualizacion` int DEFAULT NULL,
  `SI1` varchar(200) DEFAULT NULL,
  `paqueteSI1` varchar(200) DEFAULT NULL,
  `SI2` varchar(200) DEFAULT NULL,
  `paqueteSI2` varchar(200) DEFAULT NULL,
  `SI3` varchar(200) DEFAULT NULL,
  `paqueteSI3` varchar(200) DEFAULT NULL,
  `SI4` varchar(200) DEFAULT NULL,
  `paqueteSI4` varchar(200) DEFAULT NULL,
  `SI5` varchar(200) DEFAULT NULL,
  `paqueteSI5` varchar(200) DEFAULT NULL,
  `S1` varchar(200) DEFAULT NULL,
  `paqueteS1` varchar(200) DEFAULT NULL,
  `S2` varchar(200) DEFAULT NULL,
  `paqueteS2` varchar(200) DEFAULT NULL,
  `S3` varchar(200) DEFAULT NULL,
  `paqueteS3` varchar(200) DEFAULT NULL,
  `S4` varchar(200) DEFAULT NULL,
  `paqueteS4` varchar(200) DEFAULT NULL,
  `S5` varchar(200) DEFAULT NULL,
  `paqueteS5` varchar(200) DEFAULT NULL,
  `MO1` varchar(200) DEFAULT NULL,
  `paqueteMO1` varchar(200) DEFAULT NULL,
  `MO2` varchar(200) DEFAULT NULL,
  `paqueteMO2` varchar(200) DEFAULT NULL,
  `MO3` varchar(200) DEFAULT NULL,
  `paqueteMO3` varchar(200) DEFAULT NULL,
  `MO4` varchar(200) DEFAULT NULL,
  `paqueteMO4` varchar(200) DEFAULT NULL,
  `MO5` varchar(200) DEFAULT NULL,
  `paqueteMO5` varchar(200) DEFAULT NULL,
  `OC1` varchar(200) DEFAULT NULL,
  `paqueteOC1` varchar(200) DEFAULT NULL,
  `OC2` varchar(200) DEFAULT NULL,
  `paqueteOC2` varchar(200) DEFAULT NULL,
  `OC3` varchar(200) DEFAULT NULL,
  `paqueteOC3` varchar(200) DEFAULT NULL,
  `OC4` varchar(200) DEFAULT NULL,
  `paqueteOC4` varchar(200) DEFAULT NULL,
  `OC5` varchar(200) DEFAULT NULL,
  `paqueteOC5` varchar(200) DEFAULT NULL,
  `numeroSubcontratos` tinyint NOT NULL DEFAULT '1',
  `confianza_deteccion` decimal(5,2) DEFAULT NULL,
  `ultimo_auto_definir` datetime DEFAULT NULL,
  `fechaInicioProyectada` date DEFAULT NULL,
  PRIMARY KEY (`project_id`,`Id`),
  KEY `idx_project_actividad` (`project_id`,`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `auto_contrato_log` (
  `project_id` int NOT NULL,
  `id` int NOT NULL AUTO_INCREMENT,
  `semana` int NOT NULL,
  `Id_actividad` int NOT NULL,
  `accion` enum('asignar','deshacer') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `tipo_contrato` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paquetes` json DEFAULT NULL,
  `confianza` decimal(5,2) DEFAULT NULL,
  `fecha_inicio_proyectada` date DEFAULT NULL,
  `num_proveedores` tinyint DEFAULT NULL,
  `usuario` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `batch_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `creado_en` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_project_auto_contrato` (`project_id`,`id`),
  KEY `idx_batch_id` (`batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `auto_program_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `project_id` int DEFAULT NULL,
  `semana` int NOT NULL,
  `consecutivo` int NOT NULL,
  `unique_id` int DEFAULT NULL,
  `accion` enum('comprometer','descomprometer','insert_cnp') COLLATE utf8mb4_unicode_ci NOT NULL,
  `detalle` text COLLATE utf8mb4_unicode_ci,
  `categoria_cnp` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cnp` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `creado_en` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_semana` (`semana`),
  KEY `idx_consecutivo` (`consecutivo`),
  KEY `idx_apl_project_unique_week` (`project_id`,`unique_id`,`semana`),
  CONSTRAINT `fk_apl__programa__unique_id` FOREIGN KEY (`project_id`, `unique_id`) REFERENCES `programa` (`project_id`, `unique_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1852 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `cambios` (
  `project_id` int NOT NULL,
  `id` int NOT NULL,
  `solicitanteCambio` int DEFAULT NULL,
  `detalleSolicitanteOtro` longtext,
  `fechaSolicitud` date DEFAULT NULL,
  `prioridad` int DEFAULT NULL,
  `tipoCambio` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `responsableSolucion` int DEFAULT NULL,
  `detalleResponsableSolucion` longtext,
  `justificacion` longtext,
  `descripcion` longtext,
  `incidenciaAlcance` longtext,
  `tiempoCronograma` float DEFAULT NULL,
  `tiempoCronogramaAfectado` float DEFAULT NULL,
  `incidenciaCronograma` longtext,
  `valorPresupuesto` float DEFAULT NULL,
  `costoDirecto` float DEFAULT NULL,
  `costoDirectoAIU` float DEFAULT NULL,
  `costoDirectoAIUIVA` float DEFAULT NULL,
  `valorAprobado` float DEFAULT NULL,
  `incidenciaPresupuesto` longtext,
  `incidenciaCalidad` longtext,
  `incidenciaRiesgo` longtext,
  `incidenciaRecurso` longtext,
  `fechaTentativaDefinicion` date DEFAULT NULL,
  `fechaEntregaInterventoria` date DEFAULT NULL,
  `Observaciones` longtext,
  `fechaDefinicion` date DEFAULT NULL,
  `aprobacion` int DEFAULT NULL,
  `soportes` longtext,
  PRIMARY KEY (`project_id`,`id`),
  KEY `idx_project_cambios` (`project_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `cic` (
  `project_id` int NOT NULL,
  `Id` int NOT NULL,
  `Semana` int DEFAULT NULL,
  `subcontratista` varchar(200) DEFAULT NULL,
  `correo_contacto` varchar(200) DEFAULT NULL,
  `NIT` varchar(10) DEFAULT NULL,
  `alcance` varchar(200) DEFAULT NULL,
  `tipo_proveedor` varchar(200) DEFAULT NULL,
  `PAC` varchar(11) DEFAULT 'NA',
  `PAC_Acum` varchar(11) DEFAULT 'NA',
  `P_Completado` varchar(11) DEFAULT 'NA',
  `P_Completado_Acum` varchar(11) DEFAULT 'NA',
  `Calidad` varchar(11) NOT NULL DEFAULT 'NR',
  `Calidad_Acum` varchar(11) NOT NULL DEFAULT 'NR',
  `GSA` varchar(11) NOT NULL DEFAULT 'NR',
  `GSA_Acum` varchar(11) NOT NULL DEFAULT 'NR',
  `SST` varchar(11) NOT NULL DEFAULT 'NR',
  `SST_Acum` varchar(11) NOT NULL DEFAULT 'NR',
  `ADM` varchar(11) NOT NULL DEFAULT 'NR',
  `ADM_Acum` varchar(11) NOT NULL DEFAULT 'NR',
  `Cal_Integral` float DEFAULT NULL,
  `Cal_Integral_Acum` float DEFAULT NULL,
  `Observaciones` mediumtext,
  `mdo_cal_1` varchar(5) DEFAULT 'NR',
  `mdo_cal_2` varchar(5) DEFAULT 'NR',
  `mdo_cal_3` varchar(5) DEFAULT 'NR',
  `mdo_adm_1` varchar(5) DEFAULT 'NR',
  `mdo_adm_2` varchar(5) DEFAULT 'NR',
  `mdo_adm_3` varchar(5) DEFAULT 'NR',
  `mdo_adm_4` varchar(5) DEFAULT 'NR',
  `mdo_adm_5` varchar(5) DEFAULT 'NR',
  `mdo_gsa_1` varchar(5) DEFAULT 'NR',
  `mdo_gsa_2` varchar(5) DEFAULT 'NR',
  `mdo_gsa_3` varchar(5) DEFAULT 'NR',
  `mdo_gsa_4` varchar(5) DEFAULT 'NR',
  `mdo_gsa_5` varchar(5) DEFAULT 'NR',
  `mdo_gsa_6` varchar(5) DEFAULT 'NR',
  `mdo_gsa_7` varchar(5) DEFAULT 'NR',
  `mdo_gsa_8` varchar(5) DEFAULT 'NR',
  `mdo_sst_1` varchar(5) DEFAULT 'NR',
  `mdo_sst_2` varchar(5) DEFAULT 'NR',
  `mdo_sst_3` varchar(5) DEFAULT 'NR',
  `mdo_sst_4` varchar(5) DEFAULT 'NR',
  `mdo_sst_5` varchar(5) DEFAULT 'NR',
  `mdo_sst_6` varchar(5) DEFAULT 'NR',
  `mdo_sst_7` varchar(5) DEFAULT 'NR',
  `mdo_sst_8` varchar(5) DEFAULT 'NR',
  `mdo_sst_9` varchar(5) DEFAULT 'NR',
  `mdo_sst_10` varchar(5) DEFAULT 'NR',
  `si_cal_1` varchar(5) DEFAULT 'NR',
  `si_cal_2` varchar(5) DEFAULT 'NR',
  `si_cal_3` varchar(5) DEFAULT 'NR',
  `si_adm_1` varchar(5) DEFAULT 'NR',
  `si_adm_2` varchar(5) DEFAULT 'NR',
  `si_adm_3` varchar(5) DEFAULT 'NR',
  `si_adm_4` varchar(5) DEFAULT 'NR',
  `si_adm_5` varchar(5) DEFAULT 'NR',
  `si_adm_6` varchar(5) DEFAULT 'NR',
  `si_gsa_1` varchar(5) DEFAULT 'NR',
  `si_gsa_2` varchar(5) DEFAULT 'NR',
  `si_gsa_3` varchar(5) DEFAULT 'NR',
  `si_gsa_4` varchar(5) DEFAULT 'NR',
  `si_gsa_5` varchar(5) DEFAULT 'NR',
  `si_gsa_6` varchar(5) DEFAULT 'NR',
  `si_gsa_7` varchar(5) DEFAULT 'NR',
  `si_gsa_8` varchar(5) DEFAULT 'NR',
  `si_gsa_9` varchar(5) DEFAULT 'NR',
  `si_gsa_10` varchar(5) DEFAULT 'NR',
  `si_gsa_11` varchar(5) DEFAULT 'NR',
  `si_gsa_12` varchar(5) DEFAULT 'NR',
  `si_gsa_13` varchar(5) DEFAULT 'NR',
  `si_gsa_14` varchar(5) DEFAULT 'NR',
  `si_sst_1` varchar(5) DEFAULT 'NR',
  `si_sst_2` varchar(5) DEFAULT 'NR',
  `si_sst_3` varchar(5) DEFAULT 'NR',
  `si_sst_4` varchar(5) DEFAULT 'NR',
  `si_sst_5` varchar(5) DEFAULT 'NR',
  `si_sst_6` varchar(5) DEFAULT 'NR',
  `si_sst_7` varchar(5) DEFAULT 'NR',
  `si_sst_8` varchar(5) DEFAULT 'NR',
  `si_sst_9` varchar(5) DEFAULT 'NR',
  `si_sst_10` varchar(5) DEFAULT 'NR',
  PRIMARY KEY (`project_id`,`Id`),
  KEY `idx_project_cic` (`project_id`,`Id`),
  KEY `fk_cic__subcontratistas__subcontratista` (`project_id`,`subcontratista`),
  CONSTRAINT `fk_cic__subcontratistas__subcontratista` FOREIGN KEY (`project_id`, `subcontratista`) REFERENCES `subcontratistas` (`project_id`, `subcontratista`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `cip` (
  `project_id` int NOT NULL,
  `Id` int NOT NULL AUTO_INCREMENT,
  `Semana` int DEFAULT NULL,
  `profesional` varchar(200) DEFAULT NULL,
  `correo_contacto` varchar(200) DEFAULT NULL,
  `PAC` varchar(11) DEFAULT 'NA',
  `PAC_Acum` varchar(11) DEFAULT 'NA',
  `P_Completado` varchar(11) DEFAULT 'NA',
  `P_Completado_Acum` varchar(11) DEFAULT 'NA',
  `Act_Criticas_Cumplidas` varchar(11) DEFAULT 'NA',
  `Act_No_Criticas_Cumplidas` varchar(11) DEFAULT 'NA',
  `Act_Atrasadas_Cumplidas` varchar(11) DEFAULT 'NA',
  `Act_Criticas_Cumplidas_Acum` varchar(11) DEFAULT 'NA',
  `Act_No_Criticas_Cumplidas_Acum` varchar(11) DEFAULT 'NA',
  `Act_Atrasadas_Cumplidas_Acum` varchar(11) DEFAULT 'NA',
  `PAC_Consolidado` varchar(11) DEFAULT 'NA',
  `PAC_Consolidado_Acum` varchar(11) DEFAULT 'NA',
  PRIMARY KEY (`Id`),
  KEY `idx_project_cip` (`project_id`,`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `indicadores_generales` (
  `project_id` int NOT NULL,
  `id` int NOT NULL AUTO_INCREMENT,
  `Semana` int DEFAULT NULL,
  `subcontratista_profesional` varchar(200) DEFAULT NULL,
  `rol` varchar(50) DEFAULT NULL,
  `PAC` varchar(11) DEFAULT 'NA',
  `P_Completado` varchar(11) DEFAULT 'NA',
  `CNC_Rendimiento` int DEFAULT '0',
  `CNC_Programacion` int DEFAULT '0',
  `CNC_MdeO` int DEFAULT '0',
  `CNC_Materiales` int DEFAULT '0',
  `CNC_Equipos` int DEFAULT '0',
  `CNC_Disenos` int DEFAULT '0',
  `CNC_Administrativas` int DEFAULT '0',
  `CNC_Causas_Exogenas` int DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_project_indicadores` (`project_id`,`Semana`,`subcontratista_profesional`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lps_drawer_comentarios` (
  `project_id` int NOT NULL,
  `id` int NOT NULL,
  `proyecto_id` int NOT NULL,
  `consecutivo_en_programa` int NOT NULL,
  `semana` int NOT NULL,
  `unique_id` int DEFAULT NULL,
  `usuario_id` int NOT NULL COMMENT 'Autor del comentario (general_usuarios)',
  `comentario` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `escalamiento_id` int DEFAULT NULL COMMENT 'Nulo si es comentario general de bitacora, ID si vincula a hilo de crisis',
  `parent_id` int DEFAULT NULL COMMENT 'Autorreferencia para soporte de hilos anidados',
  `menciones` json DEFAULT NULL COMMENT 'Metadatos de roles AIA notificados',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`,`id`),
  KEY `idx_comentario_actividad` (`consecutivo_en_programa`,`semana`),
  KEY `idx_parent` (`parent_id`),
  KEY `fk_lpsc_escal` (`escalamiento_id`),
  KEY `idx_project_drawer` (`project_id`,`id`),
  KEY `fk_ldc__lps_escalamientos__escalamiento_id` (`project_id`,`escalamiento_id`),
  KEY `fk_ldc__programa__consecutivo` (`project_id`,`consecutivo_en_programa`),
  KEY `idx_ldc_project_unique_week` (`project_id`,`unique_id`,`semana`),
  KEY `fk_ldc__semanas_activas__semana` (`project_id`,`semana`),
  KEY `fk_ldc__profesionales__usuario_id` (`project_id`,`usuario_id`),
  KEY `fk_ldc__parent__self` (`project_id`,`parent_id`),
  CONSTRAINT `fk_ldc__lps_escalamientos__escalamiento_id` FOREIGN KEY (`project_id`, `escalamiento_id`) REFERENCES `lps_escalamientos` (`project_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ldc__parent__self` FOREIGN KEY (`project_id`, `parent_id`) REFERENCES `lps_drawer_comentarios` (`project_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ldc__profesionales__usuario_id` FOREIGN KEY (`project_id`, `usuario_id`) REFERENCES `profesionales` (`project_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ldc__programa__consecutivo` FOREIGN KEY (`project_id`, `consecutivo_en_programa`) REFERENCES `programa` (`project_id`, `Consecutivo`) ON DELETE CASCADE,
  CONSTRAINT `fk_ldc__programa__unique_id` FOREIGN KEY (`project_id`, `unique_id`) REFERENCES `programa` (`project_id`, `unique_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ldc__semanas_activas__semana` FOREIGN KEY (`project_id`, `semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `lps_escalamientos` (
  `project_id` int NOT NULL,
  `id` int NOT NULL,
  `proyecto_id` int NOT NULL COMMENT 'ID de la obra actual',
  `semana` int NOT NULL COMMENT 'Semana en la que se detono o esta activa',
  `consecutivo_en_programa` int NOT NULL COMMENT 'ID de la actividad en consolidado',
  `unique_id` int DEFAULT NULL,
  `modulo` enum('PG','PI','PS') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nivel de planificacion donde se detecta',
  `trigger_origen` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Codigo del disparador: PG-1, PG-2, PI-1, PI-2, PS-1, PS-2, PS-3',
  `nivel_actual` tinyint NOT NULL DEFAULT '1' COMMENT '1: Residente, 2: Director, 3: Coordinador Integracion, 4: G. Construccion, 5: G. General',
  `estado` enum('Activo','Mitigado','Cerrado') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Activo',
  `fecha_detonacion` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_ultimo_escalamiento` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `fecha_cierre` timestamp NULL DEFAULT NULL,
  `usuario_cierre_id` int DEFAULT NULL COMMENT 'Usuario de general_usuarios que cierra la alerta',
  `justificacion_cierre` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Justificacion obligatoria (>100 caracteres)',
  PRIMARY KEY (`project_id`,`id`),
  KEY `idx_semana_consecutivo` (`semana`,`consecutivo_en_programa`),
  KEY `idx_estado_nivel` (`estado`,`nivel_actual`),
  KEY `idx_proyecto` (`proyecto_id`),
  KEY `idx_project_escalamientos` (`project_id`,`id`),
  KEY `fk_le__programa__consecutivo` (`project_id`,`consecutivo_en_programa`),
  KEY `idx_le_project_unique_week` (`project_id`,`unique_id`,`semana`),
  KEY `fk_le__semanas_activas__semana` (`project_id`,`semana`),
  KEY `fk_le__profesionales__usuario_cierre` (`project_id`,`usuario_cierre_id`),
  CONSTRAINT `fk_le__profesionales__usuario_cierre` FOREIGN KEY (`project_id`, `usuario_cierre_id`) REFERENCES `profesionales` (`project_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_le__programa__consecutivo` FOREIGN KEY (`project_id`, `consecutivo_en_programa`) REFERENCES `programa` (`project_id`, `Consecutivo`) ON DELETE CASCADE,
  CONSTRAINT `fk_le__programa__unique_id` FOREIGN KEY (`project_id`, `unique_id`) REFERENCES `programa` (`project_id`, `unique_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_le__semanas_activas__semana` FOREIGN KEY (`project_id`, `semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `papelera_pdc` (
  `project_id` int NOT NULL,
  `pdc_row_id` int DEFAULT NULL,
  `consecutivo` int NOT NULL,
  `semana` int NOT NULL,
  `titulo` int NOT NULL,
  `tipoPaquete` varchar(200) NOT NULL,
  `paqueteContratacion` varchar(200) DEFAULT NULL,
  `contratos` varchar(200) DEFAULT NULL,
  `numeroSubcontratos` int DEFAULT '1',
  `subcontratoPaquete` int NOT NULL DEFAULT '1',
  `estado` varchar(200) DEFAULT NULL,
  `fechaElaboracionPliegos` date DEFAULT NULL,
  `diasElaboracionPliegos` int DEFAULT NULL,
  `fechaRealElaboracionPliegos` date DEFAULT NULL,
  `fechaEntregaPliegos` date DEFAULT NULL,
  `diasEntregaPliegos` int DEFAULT NULL,
  `fechaRealEntregaPliegos` date DEFAULT NULL,
  `fechaReciboPropuestas` date DEFAULT NULL,
  `diasReciboPropuestas` int DEFAULT NULL,
  `fechaRealReciboPropuestas` date DEFAULT NULL,
  `fechaCuadrosComparativos` date DEFAULT NULL,
  `diasCuadrosComparativos` int DEFAULT NULL,
  `fechaRealCuadrosComparativos` date DEFAULT NULL,
  `fechaLegalizacionContrato` date DEFAULT NULL,
  `diasLegalizacionContrato` int DEFAULT NULL,
  `fechaRealLegalizacionContrato` date DEFAULT NULL,
  `fechaFabricacion` date DEFAULT NULL,
  `diasFabricacion` int DEFAULT NULL,
  `fechaRealFabricacion` date DEFAULT NULL,
  `fechaInsumosObra` date DEFAULT NULL,
  `diasInsumosObra` int DEFAULT NULL,
  `fechaRealInsumosObra` date DEFAULT NULL,
  `fechaInicio` date DEFAULT NULL,
  `fechaInicioProyectada` date DEFAULT NULL,
  `fechaRealInicio` date DEFAULT NULL,
  `idProveedorAdjudicado` int DEFAULT NULL,
  `numeroContrato` varchar(50) DEFAULT NULL,
  `aplicaPolizas` int NOT NULL DEFAULT '1',
  `fechaVencimientoPolizas` date DEFAULT NULL,
  `valorPresupuesto` float DEFAULT NULL,
  `valorPrimeraNegociacion` float DEFAULT NULL,
  `valorAdjudicado` float DEFAULT NULL,
  `valorAnticipo` float DEFAULT NULL,
  `valorReclamado` float DEFAULT NULL,
  `valorDevoluciones` float DEFAULT NULL,
  `observacionesContrato` mediumtext,
  `justificacionEliminacion` mediumtext,
  PRIMARY KEY (`project_id`,`consecutivo`),
  KEY `idx_project_pdc` (`project_id`,`consecutivo`),
  KEY `idx_papelera_project_row_id` (`project_id`,`pdc_row_id`),
  KEY `fk_pdc__semanas_activas__semana` (`project_id`,`semana`),
  KEY `fk_pdc__profesionales__idproveedor` (`project_id`,`idProveedorAdjudicado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `pdc` (
  `project_id` int NOT NULL,
  `pdc_row_id` int DEFAULT NULL,
  `consecutivo` int NOT NULL,
  `semana` int NOT NULL,
  `titulo` int NOT NULL,
  `tipoPaquete` varchar(200) NOT NULL,
  `paqueteContratacion` varchar(200) DEFAULT NULL,
  `contratos` varchar(200) DEFAULT NULL,
  `numeroSubcontratos` int DEFAULT '1',
  `subcontratoPaquete` int NOT NULL DEFAULT '1',
  `estado` varchar(200) DEFAULT NULL,
  `fechaElaboracionPliegos` date DEFAULT NULL,
  `diasElaboracionPliegos` int DEFAULT NULL,
  `fechaRealElaboracionPliegos` date DEFAULT NULL,
  `fechaEntregaPliegos` date DEFAULT NULL,
  `diasEntregaPliegos` int DEFAULT NULL,
  `fechaRealEntregaPliegos` date DEFAULT NULL,
  `fechaReciboPropuestas` date DEFAULT NULL,
  `diasReciboPropuestas` int DEFAULT NULL,
  `fechaRealReciboPropuestas` date DEFAULT NULL,
  `fechaCuadrosComparativos` date DEFAULT NULL,
  `diasCuadrosComparativos` int DEFAULT NULL,
  `fechaRealCuadrosComparativos` date DEFAULT NULL,
  `fechaLegalizacionContrato` date DEFAULT NULL,
  `diasLegalizacionContrato` int DEFAULT NULL,
  `fechaRealLegalizacionContrato` date DEFAULT NULL,
  `fechaFabricacion` date DEFAULT NULL,
  `diasFabricacion` int DEFAULT NULL,
  `fechaRealFabricacion` date DEFAULT NULL,
  `fechaInsumosObra` date DEFAULT NULL,
  `diasInsumosObra` int DEFAULT NULL,
  `fechaRealInsumosObra` date DEFAULT NULL,
  `fechaInicio` date DEFAULT NULL,
  `fechaInicioProyectada` date DEFAULT NULL,
  `fechaRealInicio` date DEFAULT NULL,
  `idProveedorAdjudicado` int DEFAULT NULL,
  `numeroContrato` varchar(50) DEFAULT NULL,
  `aplicaPolizas` int NOT NULL DEFAULT '1',
  `fechaVencimientoPolizas` date DEFAULT NULL,
  `valorPresupuesto` float DEFAULT NULL,
  `valorPrimeraNegociacion` float DEFAULT NULL,
  `valorAdjudicado` float DEFAULT NULL,
  `valorAnticipo` float DEFAULT NULL,
  `valorReclamado` float DEFAULT NULL,
  `valorDevoluciones` float DEFAULT NULL,
  `observacionesContrato` mediumtext,
  PRIMARY KEY (`project_id`,`consecutivo`),
  KEY `idx_project_pdc` (`project_id`,`consecutivo`),
  KEY `idx_pdc_project_row_id` (`project_id`,`pdc_row_id`),
  KEY `fk_pdc__semanas_activas__semana` (`project_id`,`semana`),
  KEY `fk_pdc__profesionales__idproveedor` (`project_id`,`idProveedorAdjudicado`),
  CONSTRAINT `fk_pdc__profesionales__idproveedor` FOREIGN KEY (`project_id`, `idProveedorAdjudicado`) REFERENCES `profesionales` (`project_id`, `id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_pdc__semanas_activas__semana` FOREIGN KEY (`project_id`, `semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `pg_tracking` (
  `project_id` int NOT NULL,
  `unique_id` int DEFAULT NULL,
  `consecutivo_en_programa` int NOT NULL,
  `semana` int NOT NULL,
  `fecha_inicio` date DEFAULT NULL,
  `fecha_fin` date DEFAULT NULL,
  `estado` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `restricciones_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechas_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estado_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `titulo` tinyint(1) NOT NULL DEFAULT '0',
  `ultimo_detectado` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`,`consecutivo_en_programa`,`semana`),
  KEY `idx_semana` (`semana`),
  KEY `idx_project_pg_tracking` (`project_id`,`consecutivo_en_programa`,`semana`),
  KEY `idx_pgt_project_unique_week` (`project_id`,`unique_id`,`semana`),
  KEY `fk_pgt__semanas_activas__semana` (`project_id`,`semana`),
  CONSTRAINT `fk_pgt__programa__consecutivo` FOREIGN KEY (`project_id`, `consecutivo_en_programa`) REFERENCES `programa` (`project_id`, `Consecutivo`) ON DELETE CASCADE,
  CONSTRAINT `fk_pgt__programa__unique_id` FOREIGN KEY (`project_id`, `unique_id`) REFERENCES `programa` (`project_id`, `unique_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pgt__semanas_activas__semana` FOREIGN KEY (`project_id`, `semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `pi_shared_constraint_links` (
  `project_id` int NOT NULL,
  `Id` bigint unsigned NOT NULL,
  `SharedConstraintId` bigint unsigned NOT NULL,
  `Semana` int NOT NULL,
  `unique_id` int DEFAULT NULL,
  `ConsecutivoEnPrograma` int NOT NULL,
  `ValorAplicado` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `OverrideLocal` tinyint(1) NOT NULL DEFAULT '0',
  `AplicadoEn` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`,`Id`),
  KEY `idx_shared` (`SharedConstraintId`),
  KEY `idx_semana_consecutivo` (`Semana`,`ConsecutivoEnPrograma`),
  KEY `idx_project_shared_links` (`project_id`,`Id`),
  KEY `fk_pscl__pi_shared_constraints` (`project_id`,`SharedConstraintId`),
  KEY `fk_pscl__programa__consecutivo` (`project_id`,`ConsecutivoEnPrograma`),
  KEY `idx_pscl_project_unique_week` (`project_id`,`unique_id`,`Semana`),
  KEY `fk_pscl__semanas_activas__semana` (`project_id`,`Semana`),
  CONSTRAINT `fk_pscl__pi_shared_constraints` FOREIGN KEY (`project_id`, `SharedConstraintId`) REFERENCES `pi_shared_constraints` (`project_id`, `Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pscl__programa__consecutivo` FOREIGN KEY (`project_id`, `ConsecutivoEnPrograma`) REFERENCES `programa` (`project_id`, `Consecutivo`) ON DELETE CASCADE,
  CONSTRAINT `fk_pscl__programa__unique_id` FOREIGN KEY (`project_id`, `unique_id`) REFERENCES `programa` (`project_id`, `unique_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pscl__semanas_activas__semana` FOREIGN KEY (`project_id`, `Semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `pi_shared_constraints` (
  `project_id` int NOT NULL,
  `Id` bigint unsigned NOT NULL,
  `Semana` int NOT NULL,
  `Restriccion` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ValorObjetivo` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `Nota` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `CreadoPor` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CreadoEn` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ActualizadoEn` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`,`Id`),
  KEY `idx_semana` (`Semana`),
  KEY `idx_restriccion` (`Restriccion`),
  KEY `idx_project_shared` (`project_id`,`Id`),
  KEY `fk_psc__semanas_activas__semana` (`project_id`,`Semana`),
  CONSTRAINT `fk_psc__semanas_activas__semana` FOREIGN KEY (`project_id`, `Semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `profesionales` (
  `project_id` int NOT NULL,
  `id` int NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `cargo` varchar(100) NOT NULL,
  `activo` int NOT NULL DEFAULT '1',
  PRIMARY KEY (`project_id`,`id`),
  KEY `idx_project_profesionales` (`project_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `program_unique_id_sequences` (
  `project_id` int NOT NULL,
  `next_unique_id` int NOT NULL,
  PRIMARY KEY (`project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `programa` (
  `project_id` int NOT NULL,
  `unique_id` int DEFAULT NULL,
  `Consecutivo` int NOT NULL,
  `Id` varchar(500) DEFAULT NULL,
  `Actividad` varchar(500) DEFAULT NULL,
  `Titulo` int DEFAULT NULL,
  `Fecha_Inicio` date DEFAULT NULL,
  `Fecha_Fin` date DEFAULT NULL,
  `Ruta_Critica` int DEFAULT NULL,
  `Ejecutado` float DEFAULT '0',
  `Estado` varchar(100) DEFAULT NULL,
  `Semanas_Inicio` int DEFAULT '0',
  `Estado_Restricciones` float DEFAULT '0',
  `D_y_E` float DEFAULT '0',
  `Materiales` float DEFAULT '0',
  `MdeO` float DEFAULT '0',
  `Equipos` float DEFAULT '0',
  `Predecesora` float DEFAULT '0',
  `Pdto_Cons` float DEFAULT '0',
  `Modelo` varchar(9) DEFAULT '0',
  `Responsable_AIA` varchar(100) DEFAULT NULL,
  `Observaciones` mediumtext,
  `Ult_Act_Est` date DEFAULT NULL,
  `Ult_Act_Restr` date DEFAULT NULL,
  `restriccion_pc_1` varchar(10) DEFAULT '0%',
  `restriccion_pc_2` varchar(10) DEFAULT '0%',
  `restriccion_pc_3` varchar(10) DEFAULT '0%',
  `restriccion_pc_4` varchar(10) DEFAULT '0%',
  PRIMARY KEY (`project_id`,`Consecutivo`),
  KEY `idx_project_programa` (`project_id`,`Consecutivo`),
  UNIQUE KEY `uq_programa_project_unique_id` (`project_id`,`unique_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `programa_consolidado` (
  `project_id` int NOT NULL,
  `row_id` int DEFAULT NULL,
  `Consecutivo` int NOT NULL,
  `Semana` int NOT NULL,
  `unique_id` int DEFAULT NULL,
  `Consecutivo_en_Programa` int NOT NULL,
  `Id` varchar(500) DEFAULT NULL,
  `Actividad` varchar(500) DEFAULT NULL,
  `Titulo` int DEFAULT NULL,
  `Fecha_Inicio` date DEFAULT NULL,
  `Fecha_Fin` date DEFAULT NULL,
  `Ruta_Critica` int DEFAULT NULL,
  `Ejecutado` float DEFAULT '0',
  `Estado` varchar(100) DEFAULT NULL,
  `Semanas_Inicio` int DEFAULT '0',
  `Estado_Restricciones` float NOT NULL DEFAULT '0',
  `D_y_E` varchar(9) NOT NULL DEFAULT '0',
  `Materiales` varchar(9) NOT NULL DEFAULT '0',
  `MdeO` varchar(9) NOT NULL DEFAULT '0',
  `Equipos` varchar(9) NOT NULL DEFAULT '0',
  `Predecesora` varchar(9) NOT NULL DEFAULT '0',
  `Pdto_Cons` varchar(9) NOT NULL DEFAULT '0',
  `Modelo` varchar(9) NOT NULL DEFAULT '0',
  `Sub_Contratista` varchar(100) DEFAULT NULL,
  `Responsable_AIA` varchar(100) DEFAULT NULL,
  `Observaciones` mediumtext,
  `Ult_Act_Est` date DEFAULT NULL,
  `Ult_Act_Restr` date DEFAULT NULL,
  `Activa` int NOT NULL DEFAULT '0',
  `Ejecutado_Siguiente_Semana` float DEFAULT NULL,
  `codigo_actividad` varchar(11) DEFAULT NULL,
  `medir_productividad` int DEFAULT '0',
  `cantidad_ppto` int DEFAULT NULL,
  `unidad` varchar(20) DEFAULT NULL,
  `programaAnteriorAsociar` varchar(500) DEFAULT NULL,
  `alerta_crisis` tinyint(1) NOT NULL DEFAULT '0',
  `reprogramaciones_acumuladas` int NOT NULL DEFAULT '0',
  `dias_reprogramacion_acumulada` int NOT NULL DEFAULT '0',
  `restriccion_pc_1` varchar(10) DEFAULT '0%',
  `restriccion_pc_2` varchar(10) DEFAULT '0%',
  `restriccion_pc_3` varchar(10) DEFAULT '0%',
  `restriccion_pc_4` varchar(10) DEFAULT '0%',
  PRIMARY KEY (`project_id`,`Consecutivo`),
  KEY `idx_crisis_hot` (`Semana`,`alerta_crisis`),
  KEY `idx_consecutivo_consolidado` (`Consecutivo_en_Programa`,`Semana`),
  KEY `idx_project_consolidado` (`project_id`,`Semana`,`Consecutivo_en_Programa`),
  KEY `idx_pc_project_semana_unique_id` (`project_id`,`Semana`,`unique_id`),
  KEY `idx_pc_project_row_id` (`project_id`,`row_id`),
  KEY `fk_pc__programa__consecutivo` (`project_id`,`Consecutivo_en_Programa`),
  CONSTRAINT `fk_pc__programa__consecutivo` FOREIGN KEY (`project_id`, `Consecutivo_en_Programa`) REFERENCES `programa` (`project_id`, `Consecutivo`) ON DELETE CASCADE,
  CONSTRAINT `fk_pc__programa__unique_id` FOREIGN KEY (`project_id`, `unique_id`) REFERENCES `programa` (`project_id`, `unique_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_pc__semanas_activas__semana` FOREIGN KEY (`project_id`, `Semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `programacion_semanal` (
  `project_id` int NOT NULL,
  `row_id` int DEFAULT NULL,
  `Consecutivo` int NOT NULL,
  `Semana` int DEFAULT NULL,
  `unique_id` int DEFAULT NULL,
  `Consecutivo_En_Programa` int NOT NULL,
  `Id` varchar(500) DEFAULT NULL,
  `Actividad` varchar(500) DEFAULT NULL,
  `Descripcion` mediumtext,
  `Ubicacion` mediumtext,
  `Fecha_Inicio` date DEFAULT NULL,
  `Fecha_Fin` date DEFAULT NULL,
  `Sub_Contratista` varchar(200) DEFAULT NULL,
  `Responsable_AIA` varchar(200) DEFAULT NULL,
  `Empresa` varchar(200) NOT NULL DEFAULT 'AIA',
  `Ejecutado` float DEFAULT NULL,
  `medir_productividad` int DEFAULT '0',
  `Unidad` varchar(10) DEFAULT NULL,
  `cantidad_ppto` int DEFAULT NULL,
  `Cantidad_Sugerida` float DEFAULT NULL,
  `Compromiso` float DEFAULT NULL,
  `Ejecutado_Real` float DEFAULT NULL,
  `P_Completado` float DEFAULT NULL,
  `PAC` int DEFAULT NULL,
  `Critica` int DEFAULT NULL,
  `Atrasada` int DEFAULT NULL,
  `Activa` varchar(3) DEFAULT NULL,
  `Es_TNP` tinyint(1) NOT NULL DEFAULT '0',
  `Categoria_CP` varchar(100) DEFAULT NULL,
  `CP` varchar(255) DEFAULT NULL,
  `Observaciones_CP` text,
  `Reprogramada_Por_Usuario` tinyint(1) NOT NULL DEFAULT '0',
  `Prog_Sin_Restricciones_100` int DEFAULT NULL,
  `Categoria_CNP` varchar(100) DEFAULT NULL,
  `CNP` varchar(100) DEFAULT NULL,
  `Observaciones_CNP` mediumtext,
  `Categoria_CNC` varchar(100) DEFAULT NULL,
  `CNC` varchar(100) DEFAULT NULL,
  `Observaciones_CNC` mediumtext,
  `Rendimientos` varchar(500) DEFAULT NULL,
  `codigo_actividad` varchar(11) DEFAULT NULL,
  `alerta_crisis` tinyint(1) NOT NULL DEFAULT '0',
  `reprogramaciones_semanales` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`project_id`,`Consecutivo`),
  KEY `idx_crisis_semanal` (`Semana`,`alerta_crisis`),
  KEY `idx_consecutivo_semanal` (`Consecutivo_En_Programa`,`Semana`),
  KEY `idx_project_semanal` (`project_id`,`Semana`,`Consecutivo_En_Programa`),
  KEY `idx_ps_project_semana_unique_id` (`project_id`,`Semana`,`unique_id`),
  KEY `idx_ps_project_row_id` (`project_id`,`row_id`),
  KEY `fk_ps__programa__consecutivo` (`project_id`,`Consecutivo_En_Programa`),
  CONSTRAINT `fk_ps__programa__consecutivo` FOREIGN KEY (`project_id`, `Consecutivo_En_Programa`) REFERENCES `programa` (`project_id`, `Consecutivo`) ON DELETE CASCADE,
  CONSTRAINT `fk_ps__programa__unique_id` FOREIGN KEY (`project_id`, `unique_id`) REFERENCES `programa` (`project_id`, `unique_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ps__semanas_activas__semana` FOREIGN KEY (`project_id`, `Semana`) REFERENCES `semanas_activas` (`project_id`, `Semana`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `semanas_activas` (
  `project_id` int NOT NULL,
  `Id` int NOT NULL,
  `Semana` int NOT NULL,
  `Fecha_Inicio_Sem` date NOT NULL,
  `Fecha_Fin_Sem` date NOT NULL,
  `Semanal_Confirmada` int DEFAULT '0',
  `fechaCierreCompromisos` date DEFAULT NULL,
  `fecha_ultimo_saneo` datetime DEFAULT NULL,
  `fechaCreacionSemana` date DEFAULT NULL,
  `reprogramacion` int NOT NULL DEFAULT '0',
  `diferenciaEstructuraCron` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`project_id`,`Id`),
  UNIQUE KEY `uq_semanas_activas_project_semana` (`project_id`,`Semana`),
  KEY `idx_project_semana` (`project_id`,`Semana`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE IF NOT EXISTS `subcontratistas` (
  `project_id` int NOT NULL,
  `Id` int NOT NULL,
  `subcontratista` varchar(200) NOT NULL,
  `correo_contacto` varchar(200) NOT NULL,
  `NIT` bigint NOT NULL,
  `alcance` varchar(200) NOT NULL,
  `tipo_proveedor` varchar(200) NOT NULL,
  `activo` int NOT NULL DEFAULT '1',
  PRIMARY KEY (`project_id`,`Id`),
  UNIQUE KEY `uq_subcontratistas_project_subcontratista` (`project_id`,`subcontratista`),
  KEY `idx_project_subcontratistas` (`project_id`,`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
/*!40101 SET character_set_client = @saved_cs_client */;

SET FOREIGN_KEY_CHECKS = 1;
